### ISSUE TITLE
我这里的运行模型速度为一帧0.8s，机器是1080tiGPU

### ISSUE THREAD

**Issue by radiumray** [MaybeShewill-CV/lanenet-lane-detection#118]
您好：
我在笔记本电脑上运行您提供的模型速度大概是一帧0.8s，在1080ti GPU机器上会稍快一点
但还是远远达不到论文提到的52fps
想请教一下不知是哪里的问题？
I1211 09:36:25.119072 9384 laneNetRun.py:118] 单张图像车道线预测耗时: 0.81228s

最耗时的代码我没动过还是这句
    t_start = time.time()
    binary_seg_image, instance_seg_image = sess.run([binary_seg_ret, instance_seg_ret],
                                                    feed_dict={input_tensor: [image]})
    t_cost = time.time() - t_start
    log.info('单张图像车道线预测耗时: {:.5f}s'.format(t_cost))

**Comment by MaybeShewill-CV** [comment]
@radiumray gpu需要warm up你可以尝试使用多张检测 batch size设置的尽量大:)

**Comment by MaybeShewill-CV** [comment]
@radiumray 你也可以看看这个 #111

**Comment by radiumray** [comment]
@MaybeShewill-CV 多谢大哥，已解决，cuDNN的问题，一直用的cpu

**Comment by berylyellow** [comment]
@radiumray  你怎么解决的啊？我的cuda9.0，cudnn7.3.1，“预测15张图像车道线, 共耗时: 6.16852s, 平均每张耗时: 0.41123s”

**Comment by MaybeShewill-CV** [comment]
@berylyellow 首先查看你的gpu是否使用正常:)

**Comment by berylyellow** [comment]
@MaybeShewill-CV gpu倒是可以正常使用的，就是不知道前面说的gpu要warm up 是要怎么操作，求助～～

**Comment by berylyellow** [comment]
/home/hh/图片/11.png

**Comment by berylyellow** [comment]
![11](https://user-images.githubusercontent.com/36025537/50480697-79c5a680-0a18-11e9-8f06-c62be45b6f69.png)

**Comment by berylyellow** [comment]
![22](https://user-images.githubusercontent.com/36025537/50480999-27858500-0a1a-11e9-924a-2d52e2667c1e.png)

**Comment by berylyellow** [comment]
GPU占用率2%，3%这样

**Comment by berylyellow** [comment]
@MaybeShewill-CV 你好，还有个问题，为什么requirement里面要安装gpu版的tensorflow和cpu版tensorflow呢？我卸载了cpu版的后发现，报错如下：
Traceback (most recent call last):
  File "tools/test_lanenet.py", line 261, in <module>
    save_dir=args.save_dir, use_gpu=args.use_gpu, batch_size=args.batch_size)
  File "tools/test_lanenet.py", line 163, in test_lanenet_batch
    input_tensor = tf.placeholder(dtype=tf.float32, shape=[None, 256, 512, 3], name='input_tensor')
AttributeError: module 'tensorflow' has no attribute 'placeholder'

**Comment by radiumray** [comment]
@berylyellow 看你的运行控制台显示信息，还是在用的CPU

**Comment by berylyellow** [comment]
@radiumray   我把cpu版本的tensorflow卸载了似乎就好了。。显示“Expected 2D array, got 1D array instead” 不知道为什么，还有“Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA”虽然不影响运行，却不知道为啥报这个错？
![333](https://user-images.githubusercontent.com/36025537/50482372-20ae4080-0a21-11e9-8e59-b2e8367f981b.png)

**Comment by MaybeShewill-CV** [comment]
@berylyellow 因为我这里是可以选择使用GPU或者CPU的 可能你需要重新安装一下tensorflow

**Comment by MaybeShewill-CV** [comment]
@berylyellow avx2 只是个建议不是bug

**Comment by MurphyChengIsMe** [comment]
@radiumray  您好，我可以詢問您使用單張1080Ti大約達到多少幀數嗎？ 我嘗試的感覺沒有那麼低，但是也沒辦法到real-time的速度
