### ISSUE TITLE
i need some help for tensorflow

### ISSUE THREAD

**Issue by cookzhang** [MaybeShewill-CV/lanenet-lane-detection#126]
when  i run this
`python tools/test_lanenet.py --is_batch False --batch_size 1 --weights_path model_weights_file --image_path data/tusimple_test_image/0.jpg`

`I1217 19:31:03.655442 20232 test_lanenet.py:77] 开始读取图像数据并进行预处理
I1217 19:31:03.665666 20232 test_lanenet.py:83] 图像读取完毕, 耗时: 0.01010s
Traceback (most recent call last):
  File "tools/test_lanenet.py", line 250, in <module>
    test_lanenet(args.image_path, args.weights_path, args.use_gpu)
  File "tools/test_lanenet.py", line 89, in test_lanenet
    binary_seg_ret, instance_seg_ret = net.inference(input_tensor=input_tensor, name='lanenet_model')
  File "/home/zhangyi/work/opencv/lanenet-lane-detection/lanenet_model/lanenet_merge_model.py", line 148, in inference
    inference_ret = self._build_model(input_tensor=input_tensor, name='inference')
  File "/home/zhangyi/work/opencv/lanenet-lane-detection/lanenet_model/lanenet_merge_model.py", line 59, in _build_model
    name='encode')
  File "/home/zhangyi/work/opencv/lanenet-lane-detection/encoder_decoder_model/vgg_encoder.py", line 95, in encode
    out_dims=64, name='conv1_1')
  File "/home/zhangyi/work/opencv/lanenet-lane-detection/encoder_decoder_model/vgg_encoder.py", line 55, in _conv_stage
    use_bias=False, padding=pad, name='conv')
  File "/home/zhangyi/work/opencv/lanenet-lane-detection/encoder_decoder_model/cnn_basenet.py", line 66, in conv2d
    w_init = tf.contrib.layers.variance_scaling_initializer()
  File "/home/zhangyi/.local/lib/python3.6/site-packages/tensorflow/python/util/lazy_loader.py", line 53, in __getattr__
    module = self._load()
  File "/home/zhangyi/.local/lib/python3.6/site-packages/tensorflow/python/util/lazy_loader.py", line 42, in _load
    module = importlib.import_module(self.__name__)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/zhangyi/.local/lib/python3.6/site-packages/tensorflow/contrib/__init__.py", line 45, in <module>
    from tensorflow.contrib import cudnn_rnn
  File "/home/zhangyi/.local/lib/python3.6/site-packages/tensorflow/contrib/cudnn_rnn/__init__.py", line 34, in <module>
    from tensorflow.contrib.cudnn_rnn.python.layers import *
  File "/home/zhangyi/.local/lib/python3.6/site-packages/tensorflow/contrib/cudnn_rnn/python/layers/__init__.py", line 23, in <module>
    from tensorflow.contrib.cudnn_rnn.python.layers.cudnn_rnn import *
  File "/home/zhangyi/.local/lib/python3.6/site-packages/tensorflow/contrib/cudnn_rnn/python/layers/cudnn_rnn.py", line 20, in <module>
    from tensorflow.contrib.cudnn_rnn.python.ops import cudnn_rnn_ops
  File "/home/zhangyi/.local/lib/python3.6/site-packages/tensorflow/contrib/cudnn_rnn/python/ops/cudnn_rnn_ops.py", line 22, in <module>
    from tensorflow.contrib.rnn.python.ops import lstm_ops
  File "/home/zhangyi/.local/lib/python3.6/site-packages/tensorflow/contrib/rnn/__init__.py", line 92, in <module>
    from tensorflow.contrib.rnn.python.ops.gru_ops import *
  File "/home/zhangyi/.local/lib/python3.6/site-packages/tensorflow/contrib/rnn/python/ops/gru_ops.py", line 33, in <module>
    resource_loader.get_path_to_datafile("_gru_ops.so"))
  File "/home/zhangyi/.local/lib/python3.6/site-packages/tensorflow/contrib/util/loader.py", line 56, in load_op_library
    ret = load_library.load_op_library(path)
  File "/home/zhangyi/.local/lib/python3.6/site-packages/tensorflow/python/framework/load_library.py", line 60, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: /home/zhangyi/.local/lib/python3.6/site-packages/tensorflow/contrib/rnn/python/ops/_gru_ops.so: undefined symbol: _ZN15stream_executor6Stream12ThenBlasGemmENS_4blas9TransposeES2_yyyfRKNS_12DeviceMemoryIfEEiS6_ifPS4_i`

**Comment by MaybeShewill-CV** [comment]
@cookzhang --weights_path should be the ckpt file path:)

**Comment by cookzhang** [comment]
thank you for  reply，it 's fix
