### ISSUE TITLE
weight path以及载入new_lanenet_model_file问题

### ISSUE THREAD

**Issue by ethan02147** [MaybeShewill-CV/lanenet-lane-detection#139]
您好，我对DL的造诣还不太深，所以想从您提供的训练好的模型中直接执行一次着手研究，想请问您在第一步骤所提到的，您有提供已经训练好的model file利我们直接运行一张测试图像，观察他出来的结果，想请问您提供的model_file在dropbox的网站里哪一个才是训练好的模型档，而我是直接把这个模型档加到以下路径 - -weights_path“”path/to/ your/model_weights_file“”这边就好了吗？因为试了很久問題一直錯在weights_path這邊，没有头绪，望您有空能回复

**Comment by Comedian1926** [comment]
试试- -weights_path path/to/ your/model_weights_file/tusimple_lanenet_vgg_2018-10-19-13-33-56.ckpt-20000

**Comment by ethan02147** [comment]
@Comedian1926 感谢您的回覆 但我还是遇到以下问题 而我确定我的directory是没有问题的 却显示 No such file or directory 问题如下:
$ python3 tools/test_lanenet.py --is_batch False --batch_size 1 --weights_path model/tusimple_lanenet/tusimple_lanenet_vgg_2018-10-19-13-33-56.ckpt-200000  --image_path data/tusimple_test_image/0.jpg
I0114 10:35:51.665068 5733 test_lanenet.py:73] 开始读取图像数据并进行预处理
I0114 10:35:51.701531 5733 test_lanenet.py:79] 图像读取完毕, 耗时: 0.03627s
2019-01-14 10:35:57.266522: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
Traceback (most recent call last):
  File "tools/test_lanenet.py", line 246, in <module>
    test_lanenet(args.image_path, args.weights_path, args.use_gpu)
  File "tools/test_lanenet.py", line 105, in test_lanenet
    saver.restore(sess=sess, save_path=weights_path)
  File "/home/ethan/.local/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 1715, in restore
    if not checkpoint_exists(compat.as_text(save_path)):
  File "/home/ethan/.local/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 2056, in checkpoint_exists
    if file_io.get_matching_files(pathname):
  File "/home/ethan/.local/lib/python3.5/site-packages/tensorflow/python/lib/io/file_io.py", line 342, in get_matching_files
    for single_filename in filename
  File "/home/ethan/.local/lib/python3.5/site-packages/tensorflow/python/framework/errors_impl.py", line 519, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: model/tusimple_lanenet; No such file or directory

**Comment by ethan02147** [comment]
由於我的ubuntu裡有python2.7 跟python3.5 但是python2.7裡面會有找不到tensorflow module的問題 python3.5有1.10.0版本的tensorflow 所以一開始是打python3 不是python
