### ISSUE TITLE
unable to load pb file downloaded from dropbpx

### ISSUE THREAD

**Issue by jjzhu** [MaybeShewill-CV/lanenet-lane-detection#163]
using tensorflow 1.10.0 encouting model problems:

Restoring parameters from ./model/tusimple_lanenet/lanenet_model.pb
2019-02-07 14:17:03.234584: W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open ./model/tusimple_lanenet/lanenet_model.pb: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
2019-02-07 14:17:03.235286: W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open ./model/tusimple_lanenet/lanenet_model.pb: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
2019-02-07 14:17:03.235319: W tensorflow/core/framework/op_kernel.cc:1275] OP_REQUIRES failed at save_restore_tensor.cc:170 : Data loss: Unable to open table file ./model/tusimple_lanenet/lanenet_model.pb: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
Traceback (most recent call last):
  File "/home/victor/anaconda3/envs/lanenet/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1278, in _do_call
    return fn(*args)
  File "/home/victor/anaconda3/envs/lanenet/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1263, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/victor/anaconda3/envs/lanenet/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1350, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.DataLossError: Unable to open table file ./model/tusimple_lanenet/lanenet_model.pb: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
	 [[Node: save/RestoreV2 = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2/tensor_names, save/RestoreV2/shape_and_slices)]]

any ideas?

**Comment by arashtavakoli** [comment]
Same issue!!

**Comment by MaybeShewill-CV** [comment]
@arashtavakoli What's the problem?:)

**Comment by arashtavakoli** [comment]
So I tried to run this in both UBUNTO and windows and everytime I get an error regarding the model file. It basically gives me the error that jjzhu has. Als I tried the new weight parameters and it did not work
