### ISSUE TITLE
 Failed to convert object of type <class 'list'> to Tensor.

### ISSUE THREAD

**Issue by jilingling** [MaybeShewill-CV/lanenet-lane-detection#233]
训练过程中出现这个问题，tensorflow版本1.9.0，是版本问题吗？

Traceback (most recent call last):
  File "train_lanenet.py", line 712, in <module>
    train_lanenet(args.dataset_dir, args.weights_path, net_flag=args.net_flag)
  File "train_lanenet.py", line 242, in train_lanenet
    instance_label=train_instance_labels, name='lanenet_model'
  File "/home/jll/Projects/lanenet-lane-detection-master/lanenet_model/lanenet.py", line 93, in compute_loss
    reuse=self._reuse
  File "/home/jll/Projects/lanenet-lane-detection-master/lanenet_model/lanenet_back_end.py", line 86, in compute_loss
    binary_label.get_shape().as_list()[2]]),
  File "/home/jll/anaconda3/envs/py35/lib/python3.5/site-packages/tensorflow/python/ops/gen_array_ops.py", line 6197, in reshape
    "Reshape", tensor=tensor, shape=shape, name=name)
  File "/home/jll/anaconda3/envs/py35/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 513, in _apply_op_helper
    raise err
  File "/home/jll/anaconda3/envs/py35/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 510, in _apply_op_helper
    preferred_dtype=default_dtype)
  File "/home/jll/anaconda3/envs/py35/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1107, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/home/jll/anaconda3/envs/py35/lib/python3.5/site-packages/tensorflow/python/framework/constant_op.py", line 217, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/home/jll/anaconda3/envs/py35/lib/python3.5/site-packages/tensorflow/python/framework/constant_op.py", line 196, in constant
    value, dtype=dtype, shape=shape, verify_shape=verify_shape))
  File "/home/jll/anaconda3/envs/py35/lib/python3.5/site-packages/tensorflow/python/framework/tensor_util.py", line 525, in make_tensor_proto
    "supported type." % (type(values), values))
TypeError: Failed to convert object of type <class 'list'> to Tensor. Contents: [None, 256, 512]. Consider casting elements to a supported type.

**Comment by MaybeShewill-CV** [comment]
@jilingling 你可以尝试下切换tensorflow 1.12能否解决这个问题:)
