### ISSUE TITLE
Some problem about train 

### ISSUE THREAD

**Issue by Endless-Hao** [MaybeShewill-CV/lanenet-lane-detection#25]
I download a vgg16.npy from network.When i train the model ,i get the error .
totalMemory: 10.91GiB freeMemory: 10.75GiB
2018-07-18 16:59:10.664853: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1435] Adding visible gpu devices: 0, 1, 2, 3
2018-07-18 16:59:11.781350: I tensorflow/core/common_runtime/gpu/gpu_device.cc:923] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-07-18 16:59:11.781395: I tensorflow/core/common_runtime/gpu/gpu_device.cc:929]      0 1 2 3 
2018-07-18 16:59:11.781403: I tensorflow/core/common_runtime/gpu/gpu_device.cc:942] 0:   N Y N N 
2018-07-18 16:59:11.781408: I tensorflow/core/common_runtime/gpu/gpu_device.cc:942] 1:   Y N N N 
2018-07-18 16:59:11.781413: I tensorflow/core/common_runtime/gpu/gpu_device.cc:942] 2:   N N N Y 
2018-07-18 16:59:11.781417: I tensorflow/core/common_runtime/gpu/gpu_device.cc:942] 3:   N N Y N 
2018-07-18 16:59:11.781740: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1053] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 9496 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:02:00.0, compute capability: 6.1)
I0718 16:59:12.083954 20078 train_lanenet.py:153] Global configuration is as follows:
I0718 16:59:12.087059 20078 train_lanenet.py:154] {'TEST': {'TF_ALLOW_GROWTH': True, 'BATCH_SIZE': 32, 'GPU_MEMORY_FRACTION': 0.8}, 'TRAIN': {'LEARNING_RATE': 0.0005, 'IMG_WIDTH': 512, 'BATCH_SIZE': 4, 'EPOCHS': 200010, 'TEST_DISPLAY_STEP': 1000, 'IMG_HEIGHT': 256, 'MOMENTUM': 0.9, 'DISPLAY_STEP': 1, 'CLASSES_NUMS': 2, 'TF_ALLOW_GROWTH': True, 'VAL_BATCH_SIZE': 4, 'LR_DECAY_RATE': 0.1, 'GPU_MEMORY_FRACTION': 0.85, 'LR_DECAY_STEPS': 210000}}
I0718 16:59:12.806772 20078 train_lanenet.py:162] Training from scratch
Traceback (most recent call last):
  File "/Disk/pch/lanenet-lane-detection-master/tools/train_lanenet.py", line 307, in <module>
    train_net(args.dataset_dir, args.weights_path, net_flag=args.net)
  File "/Disk/pch/lanenet-lane-detection-master/tools/train_lanenet.py", line 245, in train_net
    = val_dataset.next_batch(CFG.TRAIN.VAL_BATCH_SIZE)
  File "/Disk/pch/lanenet-lane-detection-master/data_provider/lanenet_data_processor.py", line 95, in next_batch
    return self.next_batch(batch_size)
  File "/Disk/pch/lanenet-lane-detection-master/data_provider/lanenet_data_processor.py", line 95, in next_batch
  File "/Disk/pch/lanenet-lane-detection-master/data_provider/lanenet_data_processor.py", line 95, in next_batch
    return self.next_batch(batch_size)
  File "/Disk/pch/lanenet-lane-detection-master/data_provider/lanenet_data_processor.py", line 93, in next_batch
    self._random_dataset()
  File "/Disk/pch/lanenet-lane-detection-master/data_provider/lanenet_data_processor.py", line 66, in _random_dataset
    random_idx = np.random.permutation(len(self._gt_img_list))
  File "mtrand.pyx", line 4907, in mtrand.RandomState.permutation
  File "mtrand.pyx", line 4824, in mtrand.RandomState.shuffle
RuntimeError: maximum recursion depth exceeded

how can i solve it?Do you meet the same problem?

**Comment by MaybeShewill-CV** [comment]
@Endless-Hao I did not train the model on multiple GPUs.

**Comment by Endless-Hao** [comment]
@MaybeShewill-CV  我改成一个GPU 还是遇到同样的问题

2018-07-18 18:01:04.648433: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2018-07-18 18:01:08.105790: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1356] Found device 0 with properties: 
name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.582
pciBusID: 0000:02:00.0
totalMemory: 10.91GiB freeMemory: 10.75GiB
2018-07-18 18:01:08.105825: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1435] Adding visible gpu devices: 0
2018-07-18 18:01:08.374807: I tensorflow/core/common_runtime/gpu/gpu_device.cc:923] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-07-18 18:01:08.374854: I tensorflow/core/common_runtime/gpu/gpu_device.cc:929]      0 
2018-07-18 18:01:08.374863: I tensorflow/core/common_runtime/gpu/gpu_device.cc:942] 0:   N 
2018-07-18 18:01:08.375148: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1053] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 9496 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:02:00.0, compute capability: 6.1)
I0718 18:01:08.684602 21298 train_lanenet.py:154] Global configuration is as follows:
I0718 18:01:08.687134 21298 train_lanenet.py:155] {'TEST': {'TF_ALLOW_GROWTH': True, 'BATCH_SIZE': 32, 'GPU_MEMORY_FRACTION': 0.8}, 'TRAIN': {'LEARNING_RATE': 0.0005, 'IMG_WIDTH': 512, 'BATCH_SIZE': 4, 'EPOCHS': 200010, 'TEST_DISPLAY_STEP': 1000, 'IMG_HEIGHT': 256, 'MOMENTUM': 0.9, 'DISPLAY_STEP': 1, 'CLASSES_NUMS': 2, 'TF_ALLOW_GROWTH': True, 'VAL_BATCH_SIZE': 4, 'LR_DECAY_RATE': 0.1, 'GPU_MEMORY_FRACTION': 0.85, 'LR_DECAY_STEPS': 210000}}
I0718 18:01:09.392894 21298 train_lanenet.py:163] Training from scratch
Traceback (most recent call last):
  File "/Disk/pch/lanenet-lane-detection-master/tools/train_lanenet.py", line 308, in <module>
    train_net(args.dataset_dir, args.weights_path, net_flag=args.net)
  File "/Disk/pch/lanenet-lane-detection-master/tools/train_lanenet.py", line 246, in train_net
    = val_dataset.next_batch(CFG.TRAIN.VAL_BATCH_SIZE)
  File "/Disk/pch/lanenet-lane-detection-master/data_provider/lanenet_data_processor.py", line 95, in next_batch
    return self.next_batch(batch_size)
  File "/Disk/pch/lanenet-lane-detection-master/data_provider/lanenet_data_processor.py", line 95, in next_batch
    return self.next_batch(batch_size)
  File "/Disk/pch/lanenet-lane-detection-master/data_provider/lanenet_data_processor.py", line 95, in next_batch
    return self.next_batch(batch_size)
  File "/Disk/pch/lanenet-lane-detection-master/data_provider/lanenet_data_processor.py", line 95, in next_batch
    return self.next_batch(batch_size)
  File "/Disk/pch/lanenet-lane-detection-master/data_provider/lanenet_data_processor.py", line 95, in next_batch
    return self.next_batch(batch_size)
  File "/Disk/pch/lanenet-lane-detection-master/data_provider/lanenet_data_processor.py", line 95, in next_batch
    return self.next_batch(batch_size)
  File "/Disk/pch/lanenet-lane-detection-master/data_provider/lanenet_data_processor.py", line 95, in next_batch
    return self.next_batch(batch_size)
  File "/Disk/pch/lanenet-lane-detection-master/data_provider/lanenet_data_processor.py", line 93, in next_batch
    self._random_dataset()
  File "/Disk/pch/lanenet-lane-detection-master/data_provider/lanenet_data_processor.py", line 66, in _random_dataset
    random_idx = np.random.permutation(len(self._gt_img_list))
  File "mtrand.pyx", line 4907, in mtrand.RandomState.permutation
  File "mtrand.pyx", line 4824, in mtrand.RandomState.shuffle
RuntimeError: maximum recursion depth exceeded

**Comment by y11203090135** [comment]
请问训练使用的数据集是什么？

**Comment by MaybeShewill-CV** [comment]
@y11203090135 You may check Tusimple-Lane-Dataset

**Comment by Endless-Hao** [comment]
@y11203090135  Tusimples数据库

**Comment by Endless-Hao** [comment]
@Jolntu  i did not solve it .what about you ?

**Comment by y11203090135** [comment]
@Endless-Hao 请问TuSimple数据集是JSON文件，训练时，具体怎样把数据集处理成二值和实例图呢？

**Comment by Endless-Hao** [comment]
@y11203090135  我使用作者example里面的训练数据目前没有训练成功，目前还在找问题。更多的数据我还没有生成。Tusample数据集，官方有一个程序，如何读取json文件，我觉得把json文件中对应坐标位置的像素值改成一个值，在周围扩充几个像素即可做成二值和实例图像。官方的json文件中，同一张图不同的车道线有区分的。实例图可以根据这个做。

**Comment by y11203090135** [comment]
@Endless-Hao 谢谢啦，我去查一下。

**Comment by Endless-Hao** [comment]
@y11203090135  你使用作者的 example数据有训练成功吗？

**Comment by y11203090135** [comment]
@Endless-Hao 数据预处理的时候有错，但是和你的错误不一样，我的是在读取下一个batch时，没有数据，所以我想先把数据集整理出来，在训练

**Comment by y11203090135** [comment]
@Endless-Hao 我把训练路径修改之后，可以训练

**Comment by sunmiaozju** [comment]
@Endless-Hao 我也遇到了同样的问题，似乎是因为作者给的example里train.txt，text.txt数目太少了，我尝试简单复制txt内容扩充数目，这个问题就没了

**Comment by aj96** [comment]
I also ran into this problem. In order to get this project to work using the author's provided train.txt and val.txt you have to make sure to change the batch size in the config file from 4 to 1 because there is only one validation example.

**Comment by MaybeShewill-CV** [comment]
@aj96 @Endless-Hao @sunmiaozju @y11203090135  I have fixed that bug. Now the process will raise a exception when the batch size is larger than the amount of the samples:)
