### ISSUE TITLE
ImportError: No module named 'config'

### ISSUE THREAD

**Issue by xxzcxb1314** [MaybeShewill-CV/lanenet-lane-detection#276]
how to solve it?

**Comment by xxzcxb1314** [comment]
ImportError: No module named 'config'

**Comment by xxzcxb1314** [comment]
> how to solve it?

**Comment by MaybeShewill-CV** [comment]
@xxzcxb1314 add project path to your PYTHONPATH

**Comment by xxzcxb1314** [comment]
when  I  test the model , I  meet the following problem,  please help me ！ Thank you

python test_lanenet.py --is_batch True --batch_size 2 --save_dir ./data/tusimple_test_image/ret --weights_path ./model/tusimple_lanenet_enet/tusimple_lanenet_enet_2019-05-08-11-11-01.ckpt-100000 --image_path ./data/tusimple_test_image/
I0811 20:49:44.593514 9723 test_lanenet.py:156] 开始获取图像文件路径...
Traceback (most recent call last):
  File "/home/xxz123456/anaconda3/envs/xxzproject/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 510, in _apply_op_helper
    preferred_dtype=default_dtype)
  File "/home/xxz123456/anaconda3/envs/xxzproject/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1094, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/home/xxz123456/anaconda3/envs/xxzproject/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 931, in _TensorTensorConversionFunction
    (dtype.name, t.dtype.name, str(t)))
ValueError: Tensor conversion requested dtype string for Tensor with dtype bool: 'Tensor("Const_3:0", shape=(), dtype=bool)'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test_lanenet.py", line 258, in <module>
    save_dir=args.save_dir, use_gpu=args.use_gpu, batch_size=args.batch_size)
  File "test_lanenet.py", line 164, in test_lanenet_batch
    net = lanenet_merge_model.LaneNet(phase=phase_tensor, net_flag='vgg')
  File "/home/xxz123456/anaconda3/envs/xxzproject/lanenet-enet-hnet-master/lanenet_model/lanenet_merge_model.py", line 42, in __init__
    self._decoder = fcn_decoder.FCNDecoder(phase=phase)
  File "/home/xxz123456/anaconda3/envs/xxzproject/lanenet-enet-hnet-master/encoder_decoder_model/fcn_decoder.py", line 28, in __init__
    self._is_training = self._init_phase()
  File "/home/xxz123456/anaconda3/envs/xxzproject/lanenet-enet-hnet-master/encoder_decoder_model/fcn_decoder.py", line 35, in _init_phase
    return tf.equal(self._phase, self._train_phase)
  File "/home/xxz123456/anaconda3/envs/xxzproject/lib/python3.5/site-packages/tensorflow/python/ops/gen_math_ops.py", line 2649, in equal
    "Equal", x=x, y=y, name=name)
  File "/home/xxz123456/anaconda3/envs/xxzproject/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 546, in _apply_op_helper
    inferred_from[input_arg.type_attr]))
TypeError: Input 'y' of 'Equal' Op has type bool that does not match type string of argument 'x'.

**Comment by MaybeShewill-CV** [comment]
@xxzcxb1314 Add project path to your PYTHONPATH:)

**Comment by MaybeShewill-CV** [comment]
@xxzcxb1314 Maybe you should use tensorflow 1.12 gpu:)

**Comment by xxzcxb1314** [comment]
> @xxzcxb1314 Maybe you should use tensorflow 1.12 gpu:)
thank you ，it is useful

**Comment by xxzcxb1314** [comment]
> @xxzcxb1314 Add project path to your PYTHONPATH:)

谢谢，可以加我qq聊一下吗？遇到几个问题 qq 2627084603

**Comment by chenbokaix250** [comment]
use sys.path.append('/content/lanenet/lanenet-lane-detection/config')
but problem is not solved

**Comment by jwangjie** [comment]
@mattinjersey I wonder can you be more specific how did you solve the problem? Thank you very much.

**Comment by mattinjersey** [comment]
each module in python is a folder of python files.
every module must have a blank file: __init__.py in that module folder.
Furthermore most of the modules are called by the function in the tools folder, so actually I just moved each module to the tools folder.

**Comment by jwangjie** [comment]
@mattinjersey Thanks for your quick reply, I appreciate it. I still didn't get what you did to fix the problem, if you don't mind, can you teach us step by step what you did to the original code? Thanks a lot.

**Comment by mattinjersey** [comment]
I moved the folders config and lanenet_model and model and semantic_segmentation_zoo.
Now all these files are inside the tools folder. See picture below.
![toolsFolder](https://user-images.githubusercontent.com/8679102/64055095-790d8300-cb58-11e9-8a6d-fcce29e9e6de.png)

If you look inside the config directory, you will see that I have added the init file. This is an empty file. You can create it by using an editor and just saving a blank file with that name. See image below.
![configFigure](https://user-images.githubusercontent.com/8679102/64055178-eae5cc80-cb58-11e9-9dc7-490c4ee99491.png)

**Comment by xxzcxb1314** [comment]
Thank you for your sharing.



---Original---

**Comment by jwangjie** [comment]
@mattinjersey Thank you very much. It indeed works.
