### ISSUE TITLE
Got error when training example data

### ISSUE THREAD

**Issue by xiejingjacob** [MaybeShewill-CV/lanenet-lane-detection#279]
tensorflow1.14.0, opencv4.1.0,  cuda10, gtx970, python3.6.8, Ubuntu16.04,

I can test the data, but when I try to train the data from your instruction. I got some error

2019-08-08 18:49:11.821589: W tensorflow/compiler/jit/mark_for_compilation_pass.cc:1412] (One-time warning): Not using XLA:CPU for cluster because envvar TF_XLA_FLAGS=--tf_xla_cpu_global_jit was not set.  If you want XLA:CPU, either set that envvar, or use experimental_jit_scope to enable XLA:CPU.  To confirm that XLA is active, pass --vmodule=xla_compilation_cache=1 (as a proper command-line flag, not via TF_XLA_FLAGS) or set the envvar XLA_FLAGS=--xla_hlo_profile.
2019-08-08 18:49:30.541492: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at variable_ops.cc:104 : Already exists: Resource __per_step_18/lanenet_model/vgg_backend/instance_seg/while/ArithmeticOptimizer/AddOpsRewrite_add_3/tmp_var/N10tensorflow19TemporaryVariableOp6TmpVarE
2019-08-08 18:49:30.542956: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at variable_ops.cc:104 : Already exists: Resource __per_step_18/lanenet_model/vgg_backend/instance_seg/while/ArithmeticOptimizer/AddOpsRewrite_add_3/tmp_var/N10tensorflow19TemporaryVariableOp6TmpVarE
2019-08-08 18:49:30.543039: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at variable_ops.cc:104 : Already exists: Resource __per_step_18/lanenet_model/vgg_backend/instance_seg/while/ArithmeticOptimizer/AddOpsRewrite_add_3/tmp_var/N10tensorflow19TemporaryVariableOp6TmpVarE
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1356, in _do_call
    return fn(*args)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1341, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1429, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.AlreadyExistsError: Resource __per_step_18/lanenet_model/vgg_backend/instance_seg/while/ArithmeticOptimizer/AddOpsRewrite_add_3/tmp_var/N10tensorflow19TemporaryVariableOp6TmpVarE
	 [[{{node lanenet_model/vgg_backend/instance_seg/while/ArithmeticOptimizer/AddOpsRewrite_add_3/tmp_var}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tools/train_lanenet.py", line 715, in <module>
    train_lanenet(args.dataset_dir, args.weights_path, net_flag=args.net_flag)
  File "tools/train_lanenet.py", line 438, in train_lanenet
    train_images, train_binary_labels, train_instance_labels])
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 950, in run
    run_metadata_ptr)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1173, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1350, in _do_run
    run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1370, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.AlreadyExistsError: Resource __per_step_18/lanenet_model/vgg_backend/instance_seg/while/ArithmeticOptimizer/AddOpsRewrite_add_3/tmp_var/N10tensorflow19TemporaryVariableOp6TmpVarE
	 [[{{node lanenet_model/vgg_backend/instance_seg/while/ArithmeticOptimizer/AddOpsRewrite_add_3/tmp_var}}]]

I cannot solve these error. I have tried using three different computers, but I got the same error.

Then, I tried with tensorflow1.12.0, I got the same error above.

Then I tried with tensorflow1.10.0, I got another error "module tensorflow has no random"

Do anyone meet the same problem?

Thanks

**Comment by xiejingjacob** [comment]
It is due to the version of tensorflow

change codes in train_lanet.py line398

from tensorflow.core.protobuf import rewriter_config_pb2
    sess_config = tf.ConfigProto(log_device_placement=False,allow_soft_placement=True)
    sess_config.gpu_options.per_process_gpu_memory_fraction = CFG.TRAIN.GPU_MEMORY_FRACTION
    sess_config.gpu_options.allow_growth = CFG.TRAIN.TF_ALLOW_GROWTH
    sess_config.gpu_options.allocator_type = 'BFC'
    off = rewriter_config_pb2.RewriterConfig.OFF
    sess_config.graph_options.rewrite_options.arithmetic_optimization = off
    sess = tf.Session(config=sess_config)
