### ISSUE TITLE
The training problem

### ISSUE THREAD

**Issue by Kimbo-Chang** [MaybeShewill-CV/lanenet-lane-detection#309]
**1、Environment configuration:**
In docker Env run
GPU: GTX 1080 
tensorboard 1.12.2
tensorflow-gpu 1.12.0
numpy 1.14.5
opencv-python 4.1.1.26

**2.input command :**

python3 train_lanenet.py -d data/training_data_example/ -m 0

**3、output :**

failed to allocate 4.00G (4294967296 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
W1022 07:23:16.796204 2158 _methods.py:60] /usr/local/lib/python3.5/dist-packages/numpy/core/fromnumeric.py:2957: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)

W1022 07:23:16.796483 2158 _methods.py:80] /usr/local/lib/python3.5/dist-packages/numpy/core/_methods.py:80: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)

I1022 07:23:16.796584 2158 train_lanenet.py:454] Epoch: 1 total_loss= 31.802494 binary_seg_loss= 1.338527 instance_seg_loss= 27.333775 accuracy= 0.402401 fp= 0.976047 fn= 0.597599 lr= 0.000500 mean_cost_time=   nans 
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1334, in _do_call
    return fn(*args)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.OutOfRangeError: End of sequence
	 [[{{node val_IteratorGetNext}} = IteratorGetNext[output_shapes=[[4,256,512,3], [4,256,512,1], [4,256,512,1]], output_types=[DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](input_tensor_1/OneShotIterator)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train_lanenet.py", line 710, in <module>
    train_lanenet(args.dataset_dir, args.weights_path, net_flag=args.net_flag)
  File "train_lanenet.py", line 465, in train_lanenet
    val_images, val_binary_labels, val_instance_labels])
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1328, in _do_run
    run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.OutOfRangeError: End of sequence
	 [[node val_IteratorGetNext (defined at /home/workspace/lanenet-lane-detection-master/data_provider/lanenet_data_feed_pipline.py:365)  = IteratorGetNext[output_shapes=[[4,256,512,3], [4,256,512,1], [4,256,512,1]], output_types=[DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](input_tensor_1/OneShotIterator)]]

Caused by op 'val_IteratorGetNext', defined at:
  File "train_lanenet.py", line 710, in <module>
    train_lanenet(args.dataset_dir, args.weights_path, net_flag=args.net_flag)
  File "train_lanenet.py", line 299, in train_lanenet
    CFG.TRAIN.VAL_BATCH_SIZE, 1
  File "/home/workspace/lanenet-lane-detection-master/data_provider/lanenet_data_feed_pipline.py", line 365, in inputs
    return iterator.get_next(name='{:s}_IteratorGetNext'.format(self._dataset_flags))
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/data/ops/iterator_ops.py", line 421, in get_next
    name=name)), self._output_types,
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/gen_dataset_ops.py", line 2069, in iterator_get_next
    output_shapes=output_shapes, name=name)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/util/deprecation.py", line 488, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 3274, in create_op
    op_def=op_def)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 1770, in __init__
    self._traceback = tf_stack.extract_stack()

OutOfRangeError (see above for traceback): End of sequence
	 [[node val_IteratorGetNext (defined at /home/workspace/lanenet-lane-detection-master/data_provider/lanenet_data_feed_pipline.py:365)  = IteratorGetNext[output_shapes=[[4,256,512,3], [4,256,512,1], [4,256,512,1]], output_types=[DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](input_tensor_1/OneShotIterator)]]

Someon can help me~~~

**Comment by TommyTang930** [comment]
@Kimbo-Chang 
建议卸载tensorflow-gpu, tensorboard, numpy， 然后安装: 
tensorboard          1.14.0   
tensorflow-estimator 1.14.0   
tensorflow-gpu       1.14.0 
numpy                1.16.1
然后再试一下

**Comment by Kimbo-Chang** [comment]
@TommyTang930  
那我想問一下train_lanenet.py 裡面的vgg16.npy
是這個網址嗎https://github.com/machrisaa/tensorflow-vgg

**Comment by TommyTang930** [comment]
@Kimbo-Chang 
云盘地址：链接: https://pan.baidu.com/s/1P8pVEMBzChn42cnTomwrdw&shfl=shareset 提取码: vwgt

**Comment by Kimbo-Chang** [comment]
@TommyTang930 
不好意思,這樣的話cuda版本是不是要用10.0以上？
我目前是用9.0
對了,剛剛給的網址好像已經過期了

**Comment by TommyTang930** [comment]
@Kimbo-Chang 
我的CUDA版本是10.1，跑起来没有问题。
链接: https://pan.baidu.com/s/1hJ3EGJnwnqkYSmt3Ue6c8g&shfl=shareset 提取码: jq4c 
你再试一下，如果还不行，留个邮箱，我给你发过去。

**Comment by Kimbo-Chang** [comment]
還是不行ㄝ
e-mail
kimbo543@gmail.com
2289204758＠qq.com
兩個信箱找一個寄就可以了,謝謝

**Comment by yuanqiyin** [comment]
我想问一下，我在训练时显存爆了，应该怎么做调整？
下面是具体的错误：
2021-08-19 15:36:18.404978: W tensorflow/core/framework/op_kernel.cc:1651] OP_REQUIRES failed at conv_grad_input_ops.cc:1063 : Resource exhausted: OOM when allocating tensor with shape[4,64,256,512] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
2021-08-19 15:36:18.405782: I tensorflow/stream_executor/cuda/cuda_driver.cc:831] failed to allocate 2.70G (2898054144 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2021-08-19 15:36:18.405864: I tensorflow/stream_executor/cuda/cuda_driver.cc:831] failed to allocate 2.70G (2898054144 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
