### ISSUE TITLE
AttributeError: __enter__

### ISSUE THREAD

**Issue by trustablecoder** [MaybeShewill-CV/lanenet-lane-detection#334]
Here is the error:

Traceback (most recent call last):
  File "tools/test_lanenet.py", line 148, in <module>
    test_lanenet(args.image_path, args.weights_path)
  File "tools/test_lanenet.py", line 85, in test_lanenet
    binary_seg_ret, instance_seg_ret = net.inference(input_tensor=input_tensor, name='lanenet_model')
  File "/home/simge/lanenet-lane-detection-master/lanenet_model/lanenet.py", line 52, in inference
    reuse=self._reuse
  File "/home/simge/lanenet-lane-detection-master/lanenet_model/lanenet_front_end.py", line 43, in build_model
    reuse=reuse
  File "/home/simge/lanenet-lane-detection-master/semantic_segmentation_zoo/vgg16_based_fcn.py", line 357, in build_model
    self._vgg16_fcn_encode(input_tensor=input_tensor, name='vgg16_encode_module')
  File "/home/simge/lanenet-lane-detection-master/semantic_segmentation_zoo/vgg16_based_fcn.py", line 137, in _vgg16_fcn_encode
    need_layer_norm=True
  File "/home/simge/lanenet-lane-detection-master/semantic_segmentation_zoo/vgg16_based_fcn.py", line 59, in _vgg16_conv_stage
    with (name):
AttributeError: _ _enter_ _

I couldn't find how to fix "AttributeError: _ _enter_ _" error. Could you please help?

**Comment by MaybeShewill-CV** [comment]
@trustablecoder Maybe something wrong with your TensorFlow. You may install tensorflow-gpu=1.12.0 to test if the problem still exist:)
