### ISSUE TITLE
tusimple_lanenet_vgg.ckpt doesn't exist in the dropbox dir

### ISSUE THREAD

**Issue by Aya-S** [MaybeShewill-CV/lanenet-lane-detection#345]

**Comment by MaybeShewill-CV** [comment]
@Aya-S You may check this https://www.dropbox.com/sh/tnsf0lw6psszvy4/AAA81r53jpUI3wLsRW6TiPCya?dl=0

**Comment by Aya-S** [comment]
@MaybeShewill-CV  thanks for the response!
I managed to download the  files from dropbox and now trying to run the command in the read me 
> python tools/test_lanenet.py --weights_path ./model/tusimple_lanenet_vgg/tusimple_lanenet_vgg.ckpt 
--image_path ./data/tusimple_test_image/0.jpg

but there is no file named "tusimple_lanenet_vgg.ckpt" in the downloaded folder

**Comment by Aya-S** [comment]
I0121 18:36:53.065968 6043 saver.py:1284] Restoring parameters from /home/aya/Aigorithm/lanenet-lane-detection/model/new_weights/tusimple_lanenet_vgg.ckpt
2020-01-21 18:36:53.243252: W tensorflow/core/framework/op_kernel.cc:1651] OP_REQUIRES failed at save_restore_v2_ops.cc:184 : Out of range: Read less bytes than requested
Traceback (most recent call last):
  File "/home/aya/anaconda2/envs/lanenet/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1365, in _do_call
    return fn(*args)
  File "/home/aya/anaconda2/envs/lanenet/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1350, in _run_fn
    target_list, run_metadata)
  File "/home/aya/anaconda2/envs/lanenet/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1443, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.OutOfRangeError: Read less bytes than requested
	 [[{{node save/RestoreV2}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tools/test_lanenet.py", line 156, in <module>
    test_lanenet(args.image_path, args.weights_path)
  File "tools/test_lanenet.py", line 109, in test_lanenet
    saver.restore(sess=sess, save_path=weights_path)
  File "/home/aya/anaconda2/envs/lanenet/lib/python3.7/site-packages/tensorflow_core/python/training/saver.py", line 1290, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/home/aya/anaconda2/envs/lanenet/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 956, in run
    run_metadata_ptr)
  File "/home/aya/anaconda2/envs/lanenet/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1180, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/aya/anaconda2/envs/lanenet/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1359, in _do_run
    run_metadata)
  File "/home/aya/anaconda2/envs/lanenet/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1384, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.OutOfRangeError: Read less bytes than requested
	 [[node save/RestoreV2 (defined at /home/aya/anaconda2/envs/lanenet/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py:1748) ]]

**Comment by Aya-S** [comment]
My downloaded model files were corrupt. I'm now able to run the test program but with those changes to the requirements.txt
 tensorflow==1.15.0
opencv-python==4.0.0.21
