### ISSUE TITLE
大神你好，在训练过程中报错这样，请问为什么

### ISSUE THREAD

**Issue by liuyanglab** [MaybeShewill-CV/lanenet-lane-detection#359]
2020-03-14 18:05:36.569108: I tensorflow/core/kernels/data/shuffle_dataset_op.cc:111] Filling up shuffle buffer (this may take a while): 926 of 1000
2020-03-14 18:05:37.442757: I tensorflow/core/kernels/data/shuffle_dataset_op.cc:162] Shuffle buffer filled.
2020-03-14 18:05:46.693289: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at variable_ops.cc:104 : Already exists: Resource __per_step_18/lanenet_model/vgg_backend/instance_seg/while/ArithmeticOptimizer/AddOpsRewrite_add_3/tmp_var/struct tensorflow::TemporaryVariableOp::TmpVar
2020-03-14 18:05:46.693168: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at variable_ops.cc:104 : Already exists: Resource __per_step_18/lanenet_model/vgg_backend/instance_seg/while/ArithmeticOptimizer/AddOpsRewrite_add_3/tmp_var/struct tensorflow::TemporaryVariableOp::TmpVar
2020-03-14 18:05:46.694807: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at variable_ops.cc:104 : Already exists: Resource __per_step_18/lanenet_model/vgg_backend/instance_seg/while/ArithmeticOptimizer/AddOpsRewrite_add_3/tmp_var/struct tensorflow::TemporaryVariableOp::TmpVar
Traceback (most recent call last):
  File "D:\Anaconda\envs\py36\lib\site-packages\tensorflow\python\client\session.py", line 1356, in _do_call
    return fn(*args)
  File "D:\Anaconda\envs\py36\lib\site-packages\tensorflow\python\client\session.py", line 1341, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "D:\Anaconda\envs\py36\lib\site-packages\tensorflow\python\client\session.py", line 1429, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.AlreadyExistsError: Resource __per_step_18/lanenet_model/vgg_backend/instance_seg/while/ArithmeticOptimizer/AddOpsRewrite_add_3/tmp_var/struct tensorflow::TemporaryVariableOp::TmpVar
         [[{{node lanenet_model/vgg_backend/instance_seg/while/ArithmeticOptimizer/AddOpsRewrite_add_3/tmp_var}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train_lanenet.py", line 716, in <module>
    train_lanenet(args.dataset_dir, args.weights_path, net_flag=args.net_flag)
  File "train_lanenet.py", line 439, in train_lanenet
    train_images, train_binary_labels, train_instance_labels])
  File "D:\Anaconda\envs\py36\lib\site-packages\tensorflow\python\client\session.py", line 950, in run
    run_metadata_ptr)
  File "D:\Anaconda\envs\py36\lib\site-packages\tensorflow\python\client\session.py", line 1173, in _run
    feed_dict_tensor, options, run_metadata)
  File "D:\Anaconda\envs\py36\lib\site-packages\tensorflow\python\client\session.py", line 1350, in _do_run
    run_metadata)
  File "D:\Anaconda\envs\py36\lib\site-packages\tensorflow\python\client\session.py", line 1370, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.AlreadyExistsError: Resource __per_step_18/lanenet_model/vgg_backend/instance_seg/while/ArithmeticOptimizer/AddOpsRewrite_add_3/tmp_var/struct tensorflow::TemporaryVariableOp::TmpVar
         [[{{node lanenet_model/vgg_backend/instance_seg/while/ArithmeticOptimizer/AddOpsRewrite_add_3/tmp_var}}]]

(py36) E:\graduation_project\lanenet-lane-detection-master\lanenet-lane-detection-master\tools>

**Comment by liuyanglab** [comment]
还有一个问题，实例分割和二值分割用的是不同的stage，既然实例分割能识别车道线，那二值分割的意义是什么呢，感谢大神，麻烦您了

**Comment by MaybeShewill-CV** [comment]
@liuyanglab https://github.com/MaybeShewill-CV/lanenet-lane-detection/blob/master/data_provider/lanenet_data_feed_pipline.py line 357  试下减小buffer size

**Comment by liuyanglab** [comment]
我改小了，但是还是会有Already exists这个错误，我是用cpu训练的，第一次是成功了，会显示loss,time这些，但之后再训练时就会报错这个什么什么Already exists，请问大神这个怎么解决
2020-03-14 18:05:46.693289: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at variable_ops.cc:104 : Already exists: Resource __per_step_18/lanenet_model/vgg_backend/instance_seg/while/ArithmeticOptimizer/AddOpsRewrite_add_3/tmp_var/struct tensorflow::TemporaryVariableOp::TmpVar

**Comment by liuyanglab** [comment]
@MaybeShewill-CV 我改过了，但是还是会有Already exists这个错误，我是用cpu训练的，第一次是成功了，会显示loss,time这些，但之后再训练时就会报错这个Already exists，请问大神怎么解决
2020-03-14 18:05:46.693289: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at variable_ops.cc:104 : Already exists: Resource __per_step_18/lanenet_model/vgg_backend/instance_seg/while/ArithmeticOptimizer/AddOpsRewrite_add_3/tmp_var/struct tensorflow::TemporaryVariableOp::TmpVar

**Comment by liuyanglab** [comment]
@MaybeShewill-CV 谢谢您的回答，我改过了，但是还是会有Already exists这个错误，我是用cpu训练的，第一次是成功了，会显示loss,time这些，但之后再训练时就会报错这个Already exists，请问大神怎么解决
tensorflow.python.framework.errors_impl.AlreadyExistsError: Resource __per_step_18/lanenet_model/vgg_backend/instance_seg/while/ArithmeticOptimizer/AddOpsRewrite_add_3/tmp_var/struct tensorflow::TemporaryVariableOp::TmpVar
         [[{{node lanenet_model/vgg_backend/instance_seg/while/ArithmeticOptimizer/AddOpsRewrite_add_3/tmp_var}}]]
还有训练lanenet对内存有要求吗，4G够用吗？

**Comment by MaybeShewill-CV** [comment]
@liuyanglab 1.感觉是你什么文件重复写入的问题 你可以清空下工程重新试下 2.我没有用过cpu训练 太慢了 跑不动的

**Comment by liuyanglab** [comment]
@MaybeShewill-CV 我按照您说的重新试了一下，还是报错，同时注意到网上类似错误tensorflow.python.framework.errors_impl.好像是跟GPU有关，请问是不是代码中有指定GPU进行训练，另外训练日志中反复出现下述字段，请问要怎么解决？如果非要用GPU训练的话GTX1650 4G可以吗？我刚刚开始学习这方面知识，有点懵，多有打扰，还望见谅
2020-03-16 22:32:57.972531: W tensorflow/core/common_runtime/colocation_graph.cc:1016] Failed to place the graph without changing the devices of some resources. Some of the operations (that had to be colocated with resource generating operations) are not supported on the resources' devices. Current candidate devices are [
  /job:localhost/replica:0/task:0/device:CPU:0].
See below for details of this colocation group:
Colocation Debug Info:
Colocation group had the following types and supported devices:
Root Member(assigned_device_name_index_=-1 requested_device_name_='/device:GPU:1' assigned_device_name_='' resource_device_name_='/device:GPU:1' supported_device_types_=[CPU] possible_devices_=[]
Assign: CPU
Const: CPU
VariableV2: CPU
Identity: CPU
ApplyMomentum: CPU

Colocation members, user-requested devices, and framework assigned devices, if any:
  lanenet_model/vgg_frontend/vgg16_encode_module/conv3_1/bn/gamma/Initializer/ones (Const)
  lanenet_model/vgg_frontend/vgg16_encode_module/conv3_1/bn/gamma (VariableV2) /device:GPU:1
  lanenet_model/vgg_frontend/vgg16_encode_module/conv3_1/bn/gamma/Assign (Assign) /device:GPU:1
  lanenet_model/vgg_frontend/vgg16_encode_module/conv3_1/bn/gamma/read (Identity) /device:GPU:1
  lanenet_model/vgg_frontend/vgg16_encode_module/conv3_1/bn/gamma/Momentum/Initializer/zeros (Const) /device:GPU:1
  lanenet_model/vgg_frontend/vgg16_encode_module/conv3_1/bn/gamma/Momentum (VariableV2) /device:GPU:1
  lanenet_model/vgg_frontend/vgg16_encode_module/conv3_1/bn/gamma/Momentum/Assign (Assign) /device:GPU:1
  lanenet_model/vgg_frontend/vgg16_encode_module/conv3_1/bn/gamma/Momentum/read (Identity) /device:GPU:1
  Momentum/update_lanenet_model/vgg_frontend/vgg16_encode_module/conv3_1/bn/gamma/ApplyMomentum (ApplyMomentum) /device:GPU:1
  save/Assign_151 (Assign) /device:GPU:1
  save/Assign_152 (Assign) /device:GPU:1

**Comment by MaybeShewill-CV** [comment]
@liuyanglab 1.我建议你还是直接用gpu 别在cpu上折腾了 没有人在cpu上做深度学习训练 2.gtx1650也可以训练 但是batch size估计得改成1 效果应该会比较差，你可以自己实验试试

**Comment by liuyanglab** [comment]
@MaybeShewill-CV 好的，我把batch size改小以后用gpu果然可以训练了，本来以为batch size是4已经够小了，万分感谢！！

**Comment by MaybeShewill-CV** [comment]
@liuyanglab 好的 不客气 没有别的问题我close了：）
