### ISSUE TITLE
The train Problem

### ISSUE THREAD

**Issue by dpramirez** [MaybeShewill-CV/lanenet-lane-detection#368]
Tensorflow=1.14.0
Tensorflow-gpu=1.14.0
Tensorboard =1.14.0

`
I0401 23:31:38.356455 2852 train_lanenet.py:454] Epoch: 1 total_loss= 51.992935 binary_seg_loss= 1.399415 instance_seg_loss= 47.462708 accuracy= 0.307320 fp= 0.976854 fn= 0.692680 lr= 0.000500 mean_cost_time=   nans
Traceback (most recent call last):
  File "C:\Users\dpram\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\client\session.py", line 1356, in _do_call
    return fn(*args)
  File "C:\Users\dpram\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\client\session.py", line 1341, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "C:\Users\dpram\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\client\session.py", line 1429, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.OutOfRangeError: End of sequence
         [[{{node val_IteratorGetNext}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".\train_lanenet.py", line 710, in <module>
    train_lanenet(args.dataset_dir, args.weights_path, net_flag=args.net_flag)
  File ".\train_lanenet.py", line 465, in train_lanenet
    val_images, val_binary_labels, val_instance_labels])
  File "C:\Users\dpram\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\client\session.py", line 950, in run
    run_metadata_ptr)
  File "C:\Users\dpram\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\client\session.py", line 1173, in _run
    feed_dict_tensor, options, run_metadata)
  File "C:\Users\dpram\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\client\session.py", line 1350, in _do_run
    run_metadata)
  File "C:\Users\dpram\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\client\session.py", line 1370, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.OutOfRangeError: End of sequence
         [[node val_IteratorGetNext (defined at C:\Users\dpram\OneDrive\Escritorio\Avances Semanales\Codigos\lanenet-lane-detection-master\data_provider\lanenet_data_feed_pipline.py:365) ]]

Errors may have originated from an input operation.
Input Source operations connected to node val_IteratorGetNext:
 input_tensor_1/OneShotIterator (defined at C:\Users\dpram\OneDrive\Escritorio\Avances Semanales\Codigos\lanenet-lane-detection-master\data_provider\lanenet_data_feed_pipline.py:363)

Original stack trace for 'val_IteratorGetNext':
  File ".\train_lanenet.py", line 710, in <module>
    train_lanenet(args.dataset_dir, args.weights_path, net_flag=args.net_flag)
  File ".\train_lanenet.py", line 299, in train_lanenet
    CFG.TRAIN.VAL_BATCH_SIZE, 1
  File "C:\Users\dpram\OneDrive\Escritorio\Avances Semanales\Codigos\lanenet-lane-detection-master\data_provider\lanenet_data_feed_pipline.py", line 365, in inputs
    return iterator.get_next(name='{:s}_IteratorGetNext'.format(self._dataset_flags))
  File "C:\Users\dpram\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\data\ops\iterator_ops.py", line 426, in get_next
    output_shapes=self._structure._flat_shapes, name=name)
  File "C:\Users\dpram\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\ops\gen_dataset_ops.py", line 1973, in iterator_get_next
    output_shapes=output_shapes, name=name)
  File "C:\Users\dpram\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "C:\Users\dpram\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\util\deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "C:\Users\dpram\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\framework\ops.py", line 3616, in create_op
    op_def=op_def)
  File "C:\Users\dpram\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\framework\ops.py", line 2005, in __init__
    self._traceback = tf_stack.extract_stack()`

**Comment by MaybeShewill-CV** [comment]
@dpramirez Seems your tfrecords was not correctly generated:)

**Comment by FlyingSharp** [comment]
老哥，我能顺便问你一句吗？在控制台输出的每次Epoch是真的都是处理4700+图片一次的Epoch嘛？如果是的话，为什么会这么快呀？还有那个mean_cost_time是处理什么花费的时间呀？一张图片还是一次batch还是一次Epoch？

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: MaybeShewill-CV<mailto:notifications@github.com>
发送时间: 2020年4月2日 13:59
收件人: MaybeShewill-CV/lanenet-lane-detection<mailto:lanenet-lane-detection@noreply.github.com>
抄送: Subscribed<mailto:subscribed@noreply.github.com>
主题: Re: [MaybeShewill-CV/lanenet-lane-detection] The train Problem (#368)


@dpramirez<https://github.com/dpramirez> Seems your tfrecords was not correctly generated:)

―

**Comment by MaybeShewill-CV** [comment]
@FlyingSharp 你看下代码就知道了啊 这里的epoch一次就是一个batch的数据, 不是迭代完所有的数据算作一个epoch.这个看代码应该很清楚了吧. 如果你说这个不叫一个epoch的话 那也算你对 就叫一次iter吧：）

**Comment by FlyingSharp** [comment]
谢谢老哥，我就是有点懵，以为我之前的又理解错了 (。n。*)

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: MaybeShewill-CV<mailto:notifications@github.com>
发送时间: 2020年4月2日 14:32
收件人: MaybeShewill-CV/lanenet-lane-detection<mailto:lanenet-lane-detection@noreply.github.com>
抄送: FlyingSharp<mailto:coldflagship@outlook.com>; Mention<mailto:mention@noreply.github.com>
主题: Re: [MaybeShewill-CV/lanenet-lane-detection] The train Problem (#368)


@FlyingSharp<https://github.com/FlyingSharp> 你看下代码就知道了啊 这里的epoch一次就是一个batch的数据, 不是迭代完所有的数据算作一个epoch.这个看代码应该很清楚了吧. 如果你说这个不叫一个epoch的话 那也算你对 就叫一次iter吧：）

―

**Comment by MaybeShewill-CV** [comment]
@FlyingSharp 这种稍微看下代码就清楚了 不用怀疑自己：）

**Comment by FlyingSharp** [comment]
好的，谢谢老哥 ：）

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: MaybeShewill-CV <notifications@github.com>
发送时间: Thursday, April 2, 2020 3:22:53 PM
收件人: MaybeShewill-CV/lanenet-lane-detection <lanenet-lane-detection@noreply.github.com>
抄送: FlyingSharp <coldflagship@outlook.com>; Mention <mention@noreply.github.com>
主题: Re: [MaybeShewill-CV/lanenet-lane-detection] The train Problem (#368)


@FlyingSharp<https://github.com/FlyingSharp> 这种稍微看下代码就清楚了 不用怀疑自己：）

―

**Comment by dpramirez** [comment]
> @dpramirez Seems your tfrecords was not correctly generated:)

How do I verify that they are being generated correctly?

**Comment by MaybeShewill-CV** [comment]
> > @MaybeShewill-CV  Seems your tfrecords was not correctly generated:)
> 
> 
> 
> How do I verify that they are being generated correctly?

You may read the tfrecords and visualize it. Google will tell you how to read tf records.

**Comment by dpramirez** [comment]
@MaybeShewill-CV thanks for the quick responses, interest is appreciated :)
