### ISSUE TITLE
Invalid argument:Error while training lower image height and width

### ISSUE THREAD

**Issue by sainisanjay** [MaybeShewill-CV/lanenet-lane-detection#378]
I am trying to train the model with TuSimple dataset with `IMG_HEIGHT = 128` and  `IMG_WIDTH = 256`. However, i am getting error below: 
```
Traceback (most recent call last):
  File "./tools/train_lanenet.py", line 709, in <module>
    train_lanenet(args.dataset_dir, args.weights_path, net_flag=args.net_flag)
  File "./tools/train_lanenet.py", line 432, in train_lanenet
    train_images, train_binary_labels, train_instance_labels])
  File "/home/saini/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 950, in run
    run_metadata_ptr)
  File "/home/saini/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1173, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/saini/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1350, in _do_run
    run_metadata)
  File "/home/saini/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1370, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument: Input to reshape is a tensor with 156672 values, but the requested shape has 46080
	 [[{{node Reshape_2}}]]
	 [[train_IteratorGetNext]]
	 [[lanenet_model/vgg_backend/instance_seg/while/UniqueWithCounts/_109]]
  (1) Invalid argument: Input to reshape is a tensor with 156672 values, but the requested shape has 46080
	 [[{{node Reshape_2}}]]
	 [[train_IteratorGetNext]]
0 successful operations.
0 derived errors ignored.
```

 `IMG_HEIGHT = 256` and  `IMG_WIDTH = 512` training works absolutely fine.  Do i have to resized all the Tusimple dataset images into `256x512` before generating tfrecords?

**Comment by MaybeShewill-CV** [comment]
@sainisanjay You need to adjust some params in config file and regenerate the tfrecords:)

**Comment by sainisanjay** [comment]
@MaybeShewill-CV Thanks, setting `IMG_HEIGHT = 128` and `IMG_WIDTH = 256` in config file and regenerate the tfrecords works absolutely fine.
