### ISSUE TITLE
Running new model based on BiseNetV2 

### ISSUE THREAD

**Issue by apusky** [MaybeShewill-CV/lanenet-lane-detection#404]
Hello!
I am having a problem running your last weights. The original weights run great. The error I have is:
`Traceback (most recent call last):
  File "tools/test_lanenet.py", line 154, in <module>
    test_lanenet(args.image_path, args.weights_path)
  File "tools/test_lanenet.py", line 107, in test_lanenet
    saver.restore(sess=sess, save_path=weights_path)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/training/saver.py", line 1282, in restore
    checkpoint_prefix)
ValueError: The passed save_path is not a valid checkpoint: ./model/tusimple_lanenet_vgg/tusimple_lanenet_vgg.ckpt`

It seems that the model has not been saved correclty?
Thank you!

**Comment by MaybeShewill-CV** [comment]
@apusky Download the new pretrained model here https://www.dropbox.com/sh/0b6r0ljqi76kyg9/AADedYWO3bnx4PhK1BmbJkJKa?dl=0

**Comment by apusky** [comment]
@MaybeShewill-CV it's the same link as your post update. I tried again and it doesn't work. Should I change something in the code to make it work? I also tried the full PATH and it doesn't work. Thank you for your quick response

**Comment by MaybeShewill-CV** [comment]
@apusky The new model was named tusimple_lanenet.ckpt instead of tusimple_lanenet_vgg.ckpt. Please make sure you have used the right model weights file path by yourself:)

**Comment by apusky** [comment]
@MaybeShewill-CV Sorry for that silly mistake. I got it replaced and it seems that it is loading now.
When it is running I got the following error:
`During handling of the above exception, another exception occurred:`
`Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/training/saver.py", line 1300, in restore
    names_to_keys = object_graph_key_mapping(save_path)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/training/saver.py", line 1618, in object_graph_key_mapping
    object_graph_string = reader.get_tensor(trackable.OBJECT_GRAPH_PROTO_KEY)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/pywrap_tensorflow_internal.py", line 915, in get_tensor
    return CheckpointReader_GetTensor(self, compat.as_bytes(tensor_str))
tensorflow.python.framework.errors_impl.NotFoundError: Key _CHECKPOINTABLE_OBJECT_GRAPH not found in checkpoint`

`During handling of the above exception, another exception occurred:`

`Traceback (most recent call last):
  File "tools/test_lanenet.py", line 154, in <module>
    test_lanenet(args.image_path, args.weights_path)
  File "tools/test_lanenet.py", line 107, in test_lanenet
    saver.restore(sess=sess, save_path=weights_path)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/training/saver.py", line 1306, in restore
    err, "a Variable name or other graph key that is missing")
tensorflow.python.framework.errors_impl.NotFoundError: Restoring from checkpoint failed. This is most likely due to a Variable name or other graph key that is missing from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:`

`2 root error(s) found.
  (0) Not found: Key lanenet_model/vgg_backend/instance_seg/pix_bn/beta not found in checkpoint
	 [[node save/RestoreV2 (defined at /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/ops.py:1748) ]]
  (1) Not found: Key lanenet_model/vgg_backend/instance_seg/pix_bn/beta not found in checkpoint
	 [[node save/RestoreV2 (defined at /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/ops.py:1748) ]]
	 [[save/RestoreV2/_301]]
0 successful operations.
0 derived errors ignored.`

**Comment by MaybeShewill-CV** [comment]
@apusky Paste the full command you used here. Seems you have stiil used the wrong ckpt file or you did not update the code repo:）

**Comment by apusky** [comment]
@MaybeShewill-CV the command:
`python tools/test_lanenet.py --weights_path model/tusimple_lanenet_vgg/tusimple_lanenet.ckpt --image_path data/tusimple_test_image/0.jpg`
My directory tree is:

├── binary_mask_image.png
├── config
│   ├── global_config.py
│   └── __pycache__
│       └── global_config.cpython-36.pyc
├── _config.yml
├── data
│   ├── source_image
│   │   ├── accuracy.png
│   │   ├── binary_seg_loss.png
│   │   ├── instance_seg_loss.png
│   │   ├── lanenet_batch_test.gif
│   │   ├── lanenet_binary_seg.png
│   │   ├── lanenet_embedding.png
│   │   ├── lanenet_instance_seg.png
│   │   ├── lanenet_mask_result.png
│   │   ├── network_architecture.png
│   │   └── total_loss.png
│   ├── training_data_example
│   │   ├── gt_image_binary
│   │   │   ├── 0000.png
│   │   │   ├── 0001.png
│   │   │   ├── 0002.png
│   │   │   ├── 0003.png
│   │   │   ├── 0004.png
│   │   │   └── 0005.png
│   │   ├── gt_image_instance
│   │   │   ├── 0000.png
│   │   │   ├── 0001.png
│   │   │   ├── 0002.png
│   │   │   ├── 0003.png
│   │   │   ├── 0004.png
│   │   │   └── 0005.png
│   │   ├── image
│   │   │   ├── 0000.png
│   │   │   ├── 0001.png
│   │   │   ├── 0002.png
│   │   │   ├── 0003.png
│   │   │   ├── 0004.png
│   │   │   └── 0005.png
│   │   ├── train.txt
│   │   └── val.txt
│   ├── tusimple_ipm_remap.yml
│   └── tusimple_test_image
│       ├──--- 0.jpg
│       ├──--- 1.jpg
│       ├──--- 2.jpg
│       └──--- 3.jpg
├── data_provider
│   ├── lanenet_data_feed_pipline.py
│   └── tf_io_pipline_tools.py
├── instance_mask_image.png
├── lanenet_model
│   ├── lanenet_back_end.py
│   ├── lanenet_discriminative_loss.py
│   ├── lanenet_front_end.py
│   ├── lanenet_postprocess.py
│   ├── lanenet.py
│   └── __pycache__
│       ├── lanenet_back_end.cpython-36.pyc
│       ├── lanenet.cpython-36.pyc
│       ├── lanenet_discriminative_loss.cpython-36.pyc
│       ├── lanenet_front_end.cpython-36.pyc
│       └── lanenet_postprocess.cpython-36.pyc
├── LICENSE
├── mnn_project
│   ├── config.ini
│   ├── config_parser.cpp
│   ├── config_parser.h
│   ├── convert_lanenet_model_into_mnn_model.sh
│   ├── dbscan.hpp
│   ├── freeze_lanenet_model.py
│   ├── __init__.py
│   ├── kdtree.cpp
│   ├── kdtree.h
│   ├── lanenet_model.cpp
│   └── lanenet_model.h
├── model
│   ├── oldNN
│   │   ├── checkpoint
│   │   ├── tusimple_lanenet_vgg.ckpt.data-00000-of-00001
│   │   ├── tusimple_lanenet_vgg.ckpt.index
│   │   └── tusimple_lanenet_vgg.ckpt.meta
│   └── tusimple_lanenet_vgg
│       ├──--- checkpoint
│       ├──--- tusimple_lanenet.ckpt.data-00000-of-00001
│       ├──--- tusimple_lanenet.ckpt.index
│       └──--- tusimple_lanenet.ckpt.meta
├── README.md
├── requirements.txt
├── semantic_segmentation_zoo
│   ├── cnn_basenet.py
│   ├── __init__.py
│   ├── __pycache__
│   │   ├── cnn_basenet.cpython-36.pyc
│   │   ├── __init__.cpython-36.pyc
│   │   └── vgg16_based_fcn.cpython-36.pyc
│   └── vgg16_based_fcn.py
├── source_image.png
└── tools
    ├──-- evaluate_lanenet_on_tusimple.py
    ├── --evaluate_model_utils.py
    ├── --generate_tusimple_dataset.py
    ├── --test_lanenet.py
    └── --train_lanenet.py

The full output:
```
I0618 03:22:04.139261 773 test_lanenet.py:80] Start reading image and preprocessing
I0618 03:22:04.163088 773 test_lanenet.py:86] Image load complete, cost time: 0.02363s
W0618 03:22:04.163394 773 module_wrapper.py:139] From tools/test_lanenet.py:88: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

W0618 03:22:04.169868 773 module_wrapper.py:139] From /content/drive/My Drive/Colab Notebooks/lanenet-lane-detection/semantic_segmentation_zoo/vgg16_based_fcn.py:355: The name tf.variable_scope is deprecated. Please use tf.compat.v1.variable_scope instead.

W0618 03:22:04.170398 773 lazy_loader.py:50] 
The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
  * https://github.com/tensorflow/io (for I/O related ops)
If you depend on functionality not listed there, please file an issue.

I0618 03:22:04.409512 773 utils.py:141] NumExpr defaulting to 2 threads.
W0618 03:22:04.814890 773 module_wrapper.py:139] From /content/drive/My Drive/Colab Notebooks/lanenet-lane-detection/semantic_segmentation_zoo/cnn_basenet.py:70: The name tf.get_variable is deprecated. Please use tf.compat.v1.get_variable instead.

W0618 03:22:04.826056 773 deprecation.py:323] From /content/drive/My Drive/Colab Notebooks/lanenet-lane-detection/semantic_segmentation_zoo/cnn_basenet.py:342: batch_normalization (from tensorflow.python.layers.normalization) is deprecated and will be removed in a future version.
Instructions for updating:
Use keras.layers.BatchNormalization instead.  In particular, `tf.control_dependencies(tf.GraphKeys.UPDATE_OPS)` should not be used (consult the `tf.keras.layers.batch_normalization` documentation).
W0618 03:22:04.826737 773 deprecation.py:323] From /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/layers/normalization.py:327: Layer.apply (from tensorflow.python.keras.engine.base_layer) is deprecated and will be removed in a future version.
Instructions for updating:
Please use `layer.__call__` method instead.
W0618 03:22:04.875171 773 module_wrapper.py:139] From /content/drive/My Drive/Colab Notebooks/lanenet-lane-detection/semantic_segmentation_zoo/cnn_basenet.py:173: The name tf.nn.max_pool is deprecated. Please use tf.nn.max_pool2d instead.

W0618 03:22:05.269595 773 deprecation.py:323] From /content/drive/My Drive/Colab Notebooks/lanenet-lane-detection/semantic_segmentation_zoo/cnn_basenet.py:425: conv2d_transpose (from tensorflow.python.layers.convolutional) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.keras.layers.Conv2DTranspose` instead.
W0618 03:22:06.162201 773 module_wrapper.py:139] From tools/test_lanenet.py:95: The name tf.train.Saver is deprecated. Please use tf.compat.v1.train.Saver instead.

W0618 03:22:06.441568 773 module_wrapper.py:139] From tools/test_lanenet.py:98: The name tf.ConfigProto is deprecated. Please use tf.compat.v1.ConfigProto instead.

W0618 03:22:06.441898 773 module_wrapper.py:139] From tools/test_lanenet.py:103: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.

2020-06-18 03:22:06.442176: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-06-18 03:22:06.447316: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2300000000 Hz
2020-06-18 03:22:06.447588: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x2555640 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-06-18 03:22:06.447623: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-06-18 03:22:06.449913: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2020-06-18 03:22:06.525301: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:983] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-06-18 03:22:06.526220: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x2555480 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2020-06-18 03:22:06.526261: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Tesla K80, Compute Capability 3.7
2020-06-18 03:22:06.526487: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:983] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-06-18 03:22:06.527187: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1639] Found device 0 with properties: 
name: Tesla K80 major: 3 minor: 7 memoryClockRate(GHz): 0.8235
pciBusID: 0000:00:04.0
2020-06-18 03:22:06.527561: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
2020-06-18 03:22:06.528878: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
2020-06-18 03:22:06.530305: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10.0
2020-06-18 03:22:06.530682: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10.0
2020-06-18 03:22:06.532345: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10.0
2020-06-18 03:22:06.533707: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10.0
2020-06-18 03:22:06.537672: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-06-18 03:22:06.537840: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:983] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-06-18 03:22:06.538645: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:983] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-06-18 03:22:06.539329: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1767] Adding visible gpu devices: 0
2020-06-18 03:22:06.539407: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
2020-06-18 03:22:06.541351: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1180] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-06-18 03:22:06.541387: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1186]      0 
2020-06-18 03:22:06.541403: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1199] 0:   N 
2020-06-18 03:22:06.541584: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:983] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-06-18 03:22:06.542385: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:983] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-06-18 03:22:06.543092: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1325] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 9152 MB memory) -> physical GPU (device: 0, name: Tesla K80, pci bus id: 0000:00:04.0, compute capability: 3.7)
I0618 03:22:06.545681 773 saver.py:1284] Restoring parameters from model/tusimple_lanenet_vgg/tusimple_lanenet.ckpt
2020-06-18 03:22:06.726866: W tensorflow/core/framework/op_kernel.cc:1651] OP_REQUIRES failed at save_restore_v2_ops.cc:184 : Not found: Key lanenet_model/vgg_backend/instance_seg/pix_bn/beta not found in checkpoint
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py", line 1365, in _do_call
    return fn(*args)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py", line 1350, in _run_fn
    target_list, run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py", line 1443, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.NotFoundError: 2 root error(s) found.
  (0) Not found: Key lanenet_model/vgg_backend/instance_seg/pix_bn/beta not found in checkpoint
	 [[{{node save/RestoreV2}}]]
	 [[save/RestoreV2/_301]]
  (1) Not found: Key lanenet_model/vgg_backend/instance_seg/pix_bn/beta not found in checkpoint
	 [[{{node save/RestoreV2}}]]
0 successful operations.
0 derived errors ignored.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/training/saver.py", line 1290, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py", line 956, in run
    run_metadata_ptr)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py", line 1180, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py", line 1359, in _do_run
    run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py", line 1384, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.NotFoundError: 2 root error(s) found.
  (0) Not found: Key lanenet_model/vgg_backend/instance_seg/pix_bn/beta not found in checkpoint
	 [[node save/RestoreV2 (defined at /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/ops.py:1748) ]]
	 [[save/RestoreV2/_301]]
  (1) Not found: Key lanenet_model/vgg_backend/instance_seg/pix_bn/beta not found in checkpoint
	 [[node save/RestoreV2 (defined at /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/ops.py:1748) ]]
0 successful operations.
0 derived errors ignored.

Original stack trace for 'save/RestoreV2':
  File "tools/test_lanenet.py", line 154, in <module>
    test_lanenet(args.image_path, args.weights_path)
  File "tools/test_lanenet.py", line 95, in test_lanenet
    saver = tf.train.Saver()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/training/saver.py", line 828, in __init__
    self.build()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/training/saver.py", line 840, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/training/saver.py", line 878, in _build
    build_restore=build_restore)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/training/saver.py", line 508, in _build_internal
    restore_sequentially, reshape)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/training/saver.py", line 328, in _AddRestoreOps
    restore_sequentially)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/training/saver.py", line 575, in bulk_restore
    return io_ops.restore_v2(filename_tensor, names, slices, dtypes)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/ops/gen_io_ops.py", line 1696, in restore_v2
    name=name)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/op_def_library.py", line 794, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/ops.py", line 3357, in create_op
    attrs, op_def, compute_device)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/ops.py", line 3426, in _create_op_internal
    op_def=op_def)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/ops.py", line 1748, in __init__
    self._traceback = tf_stack.extract_stack()


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/training/saver.py", line 1300, in restore
    names_to_keys = object_graph_key_mapping(save_path)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/training/saver.py", line 1618, in object_graph_key_mapping
    object_graph_string = reader.get_tensor(trackable.OBJECT_GRAPH_PROTO_KEY)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/pywrap_tensorflow_internal.py", line 915, in get_tensor
    return CheckpointReader_GetTensor(self, compat.as_bytes(tensor_str))
tensorflow.python.framework.errors_impl.NotFoundError: Key _CHECKPOINTABLE_OBJECT_GRAPH not found in checkpoint

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tools/test_lanenet.py", line 154, in <module>
    test_lanenet(args.image_path, args.weights_path)
  File "tools/test_lanenet.py", line 107, in test_lanenet
    saver.restore(sess=sess, save_path=weights_path)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/training/saver.py", line 1306, in restore
    err, "a Variable name or other graph key that is missing")
tensorflow.python.framework.errors_impl.NotFoundError: Restoring from checkpoint failed. This is most likely due to a Variable name or other graph key that is missing from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:

2 root error(s) found.
  (0) Not found: Key lanenet_model/vgg_backend/instance_seg/pix_bn/beta not found in checkpoint
	 [[node save/RestoreV2 (defined at /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/ops.py:1748) ]]
	 [[save/RestoreV2/_301]]
  (1) Not found: Key lanenet_model/vgg_backend/instance_seg/pix_bn/beta not found in checkpoint
	 [[node save/RestoreV2 (defined at /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/ops.py:1748) ]]
0 successful operations.
0 derived errors ignored.

Original stack trace for 'save/RestoreV2':
  File "tools/test_lanenet.py", line 154, in <module>
    test_lanenet(args.image_path, args.weights_path)
  File "tools/test_lanenet.py", line 95, in test_lanenet
    saver = tf.train.Saver()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/training/saver.py", line 828, in __init__
    self.build()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/training/saver.py", line 840, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/training/saver.py", line 878, in _build
    build_restore=build_restore)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/training/saver.py", line 508, in _build_internal
    restore_sequentially, reshape)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/training/saver.py", line 328, in _AddRestoreOps
    restore_sequentially)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/training/saver.py", line 575, in bulk_restore
    return io_ops.restore_v2(filename_tensor, names, slices, dtypes)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/ops/gen_io_ops.py", line 1696, in restore_v2
    name=name)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/op_def_library.py", line 794, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/ops.py", line 3357, in create_op
    attrs, op_def, compute_device)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/ops.py", line 3426, in _create_op_internal
    op_def=op_def)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/ops.py", line 1748, in __init__
    self._traceback = tf_stack.extract_stack()
```

**Comment by MaybeShewill-CV** [comment]
@apusky Make sure you have git pull the new code:)

**Comment by MaybeShewill-CV** [comment]
@apusky Make sure you have downloaded the right model weighs here https://www.dropbox.com/sh/0b6r0ljqi76kyg9/AADedYWO3bnx4PhK1BmbJkJKa?dl=0

**Comment by apusky** [comment]
@MaybeShewill-CV I just pulled the repository and downloaded the weights again. It works now!
I got an inference time of 0.02316s using google colab GPU.
Thank you and have a good one!

**Comment by MaybeShewill-CV** [comment]
@apusky Welcome :)

**Comment by dpramirez** [comment]
@apusky  Hello, if it is not too much trouble, could you facilitate your collaboration, to be able to use it from there? :)

**Comment by apusky** [comment]
Hello, do you still need it? I can't see your reply on GitHub.
Regards,
Apusky
