### ISSUE TITLE
 LaneNet/bisenetv2_backend/instance_seg/pix_bn/moving_mean not found in checkpoint

### ISSUE THREAD

**Issue by SamSelvan09** [MaybeShewill-CV/lanenet-lane-detection#411]
I am facing a problem while running the test_lanenet.py file.
I am using the latest weights from DropBox
Tensor flow = 1.14.0

Thanks for the help in advance
Following is the traceback :
WARNING:tensorflow:From C:\Users\Sam\Anaconda3\envs\sam_lane_env\lib\site-packages\tensorflow\python\training\saver.py:1276: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
W0621 18:22:19.449345 4136 deprecation.py:323] From C:\Users\Sam\Anaconda3\envs\sam_lane_env\lib\site-packages\tensorflow\python\training\saver.py:1276: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
INFO:tensorflow:Restoring parameters from ./model/tusimple_lanenet_vgg/tusimple_lanenet_vgg.ckpt
I0621 18:22:19.454133 4136 saver.py:1280] Restoring parameters from ./model/tusimple_lanenet_vgg/tusimple_lanenet_vgg.ckpt
2020-06-21 18:22:19.712642: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at save_restore_v2_ops.cc:184 : Not found: Key LaneNet/bisenetv2_backend/instance_seg/pix_bn/moving_mean not found in checkpoint
Traceback (most recent call last):
  File "C:\Users\Sam\Anaconda3\envs\sam_lane_env\lib\site-packages\tensorflow\python\client\session.py", line 1356, in _do_call
    return fn(*args)
  File "C:\Users\Sam\Anaconda3\envs\sam_lane_env\lib\site-packages\tensorflow\python\client\session.py", line 1341, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "C:\Users\Sam\Anaconda3\envs\sam_lane_env\lib\site-packages\tensorflow\python\client\session.py", line 1429, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.NotFoundError: Key LaneNet/bisenetv2_backend/instance_seg/pix_bn/moving_mean not found in checkpoint
         [[{{node save/RestoreV2}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Sam\Anaconda3\envs\sam_lane_env\lib\site-packages\tensorflow\python\training\saver.py", line 1286, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "C:\Users\Sam\Anaconda3\envs\sam_lane_env\lib\site-packages\tensorflow\python\client\session.py", line 950, in run
    run_metadata_ptr)
  File "C:\Users\Sam\Anaconda3\envs\sam_lane_env\lib\site-packages\tensorflow\python\client\session.py", line 1173, in _run
    feed_dict_tensor, options, run_metadata)
  File "C:\Users\Sam\Anaconda3\envs\sam_lane_env\lib\site-packages\tensorflow\python\client\session.py", line 1350, in _do_run
    run_metadata)
  File "C:\Users\Sam\Anaconda3\envs\sam_lane_env\lib\site-packages\tensorflow\python\client\session.py", line 1370, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.NotFoundError: Key LaneNet/bisenetv2_backend/instance_seg/pix_bn/moving_mean not found in checkpoint
         [[node save/RestoreV2 (defined at test_lanenet.py:111) ]]

Original stack trace for 'save/RestoreV2':
  File "test_lanenet.py", line 160, in <module>
    test_lanenet(args['image_path'], args['weights_path'])
  File "test_lanenet.py", line 111, in test_lanenet
    saver = tf.train.Saver(variables_to_restore)
  File "C:\Users\Sam\Anaconda3\envs\sam_lane_env\lib\site-packages\tensorflow\python\training\saver.py", line 825, in __init__
    self.build()
  File "C:\Users\Sam\Anaconda3\envs\sam_lane_env\lib\site-packages\tensorflow\python\training\saver.py", line 837, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "C:\Users\Sam\Anaconda3\envs\sam_lane_env\lib\site-packages\tensorflow\python\training\saver.py", line 875, in _build
    build_restore=build_restore)
  File "C:\Users\Sam\Anaconda3\envs\sam_lane_env\lib\site-packages\tensorflow\python\training\saver.py", line 508, in _build_internal
    restore_sequentially, reshape)
  File "C:\Users\Sam\Anaconda3\envs\sam_lane_env\lib\site-packages\tensorflow\python\training\saver.py", line 328, in _AddRestoreOps
    restore_sequentially)
  File "C:\Users\Sam\Anaconda3\envs\sam_lane_env\lib\site-packages\tensorflow\python\training\saver.py", line 575, in bulk_restore
    return io_ops.restore_v2(filename_tensor, names, slices, dtypes)
  File "C:\Users\Sam\Anaconda3\envs\sam_lane_env\lib\site-packages\tensorflow\python\ops\gen_io_ops.py", line 1779, in restore_v2
    name=name)
  File "C:\Users\Sam\Anaconda3\envs\sam_lane_env\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "C:\Users\Sam\Anaconda3\envs\sam_lane_env\lib\site-packages\tensorflow\python\util\deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "C:\Users\Sam\Anaconda3\envs\sam_lane_env\lib\site-packages\tensorflow\python\framework\ops.py", line 3616, in create_op
    op_def=op_def)
  File "C:\Users\Sam\Anaconda3\envs\sam_lane_env\lib\site-packages\tensorflow\python\framework\ops.py", line 2005, in __init__
    self._traceback = tf_stack.extract_stack()

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Sam\Anaconda3\envs\sam_lane_env\lib\site-packages\tensorflow\python\training\saver.py", line 1296, in restore
    names_to_keys = object_graph_key_mapping(save_path)
  File "C:\Users\Sam\Anaconda3\envs\sam_lane_env\lib\site-packages\tensorflow\python\training\saver.py", line 1614, in object_graph_key_mapping
    object_graph_string = reader.get_tensor(trackable.OBJECT_GRAPH_PROTO_KEY)
  File "C:\Users\Sam\Anaconda3\envs\sam_lane_env\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 678, in get_tensor
    return CheckpointReader_GetTensor(self, compat.as_bytes(tensor_str))
tensorflow.python.framework.errors_impl.NotFoundError: Key _CHECKPOINTABLE_OBJECT_GRAPH not found in checkpoint

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test_lanenet.py", line 160, in <module>
    test_lanenet(args['image_path'], args['weights_path'])
  File "test_lanenet.py", line 114, in test_lanenet
    saver.restore(sess=sess, save_path=weights_path)
  File "C:\Users\Sam\Anaconda3\envs\sam_lane_env\lib\site-packages\tensorflow\python\training\saver.py", line 1302, in restore
    err, "a Variable name or other graph key that is missing")
tensorflow.python.framework.errors_impl.NotFoundError: Restoring from checkpoint failed. This is most likely due to a Variable name or other graph key that is missing from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:

Key LaneNet/bisenetv2_backend/instance_seg/pix_bn/moving_mean not found in checkpoint
         [[node save/RestoreV2 (defined at test_lanenet.py:111) ]]

Original stack trace for 'save/RestoreV2':
  File "test_lanenet.py", line 160, in <module>
    test_lanenet(args['image_path'], args['weights_path'])
  File "test_lanenet.py", line 111, in test_lanenet
    saver = tf.train.Saver(variables_to_restore)
  File "C:\Users\Sam\Anaconda3\envs\sam_lane_env\lib\site-packages\tensorflow\python\training\saver.py", line 825, in __init__
    self.build()
  File "C:\Users\Sam\Anaconda3\envs\sam_lane_env\lib\site-packages\tensorflow\python\training\saver.py", line 837, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "C:\Users\Sam\Anaconda3\envs\sam_lane_env\lib\site-packages\tensorflow\python\training\saver.py", line 875, in _build
    build_restore=build_restore)
  File "C:\Users\Sam\Anaconda3\envs\sam_lane_env\lib\site-packages\tensorflow\python\training\saver.py", line 508, in _build_internal
    restore_sequentially, reshape)
  File "C:\Users\Sam\Anaconda3\envs\sam_lane_env\lib\site-packages\tensorflow\python\training\saver.py", line 328, in _AddRestoreOps
    restore_sequentially)
  File "C:\Users\Sam\Anaconda3\envs\sam_lane_env\lib\site-packages\tensorflow\python\training\saver.py", line 575, in bulk_restore
    return io_ops.restore_v2(filename_tensor, names, slices, dtypes)
  File "C:\Users\Sam\Anaconda3\envs\sam_lane_env\lib\site-packages\tensorflow\python\ops\gen_io_ops.py", line 1779, in restore_v2
    name=name)
  File "C:\Users\Sam\Anaconda3\envs\sam_lane_env\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "C:\Users\Sam\Anaconda3\envs\sam_lane_env\lib\site-packages\tensorflow\python\util\deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "C:\Users\Sam\Anaconda3\envs\sam_lane_env\lib\site-packages\tensorflow\python\framework\ops.py", line 3616, in create_op
    op_def=op_def)
  File "C:\Users\Sam\Anaconda3\envs\sam_lane_env\lib\site-packages\tensorflow\python\framework\ops.py", line 2005, in __init__
    self._traceback = tf_stack.extract_stack()

**Comment by MaybeShewill-CV** [comment]
@SamSelvan09 1. git pull update code 2. Download new pretrained model here https://www.dropbox.com/sh/0b6r0ljqi76kyg9/AADedYWO3bnx4PhK1BmbJkJKa?dl=0

**Comment by SamSelvan09** [comment]
> 
> 
> @SamSelvan09 1. git pull update code 2. Download new pretrained model here https://www.dropbox.com/sh/0b6r0ljqi76kyg9/AADedYWO3bnx4PhK1BmbJkJKa?dl=0

Perfect, it worked :)
Thanks a lot quick response 💯
