### ISSUE TITLE
Tensor name not found in checkpoint files.

### ISSUE THREAD

**Issue by jonngai** [MaybeShewill-CV/lanenet-lane-detection#429]
Hi guys, I'm having trouble loading the checkpoint from the README:
https://www.dropbox.com/sh/tnsf0lw6psszvy4/AAA81r53jpUI3wLsRW6TiPCya?dl=0

Traceback (most recent call last):
  File "/home/jngai/lanenetEnv/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1356, in _do_call
    return fn(*args)
  File "/home/jngai/lanenetEnv/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1341, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/jngai/lanenetEnv/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1429, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.NotFoundError: Tensor name "LaneNet/bisenetv2_backend/instance_seg/pix_bn/moving_mean" not found in checkpoint files /home/jngai/laneDetect/lanenet-lane-detection/model/tusimple_lanenet_vgg/tusimple_lanenet_vgg.ckpt.index
	 [[{{node save/RestoreV2}}]]

Is there a new checkpoint I should try? Thanks.

**Comment by MaybeShewill-CV** [comment]
@jonngai Vgg based pretrained model can not be restored. Try this https://www.dropbox.com/sh/0b6r0ljqi76kyg9/AADedYWO3bnx4PhK1BmbJkJKa?dl=0 :)

**Comment by jonngai** [comment]
Thanks for responding @MaybeShewill-CV.

Still getting the same error however:
INFO:tensorflow:Restoring parameters from /home/jngai/laneDetect/lanenet-lane-detection/model/tusimple_lanenet/tusimple_lanenet.ckpt.index
I0715 09:45:26.027452 3749 saver.py:1280] Restoring parameters from /home/jngai/laneDetect/lanenet-lane-detection/model/tusimple_lanenet/tusimple_lanenet.ckpt.index
2020-07-15 09:45:26.229216: W tensorflow/compiler/jit/mark_for_compilation_pass.cc:1412] (One-time warning): Not using XLA:CPU for cluster because envvar TF_XLA_FLAGS=--tf_xla_cpu_global_jit was not set.  If you want XLA:CPU, either set that envvar, or use experimental_jit_scope to enable XLA:CPU.  To confirm that XLA is active, pass --vmodule=xla_compilation_cache=1 (as a proper command-line flag, not via TF_XLA_FLAGS) or set the envvar XLA_FLAGS=--xla_hlo_profile.
Traceback (most recent call last):
  File "/home/jngai/lanenetEnv/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1356, in _do_call
    return fn(*args)
  File "/home/jngai/lanenetEnv/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1341, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/jngai/lanenetEnv/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1429, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.NotFoundError: Tensor name "LaneNet/bisenetv2_backend/instance_seg/pix_bn/moving_mean" not found in checkpoint files /home/jngai/laneDetect/lanenet-lane-detection/model/tusimple_lanenet/tusimple_lanenet.ckpt.index
	 [[{{node save/RestoreV2}}]]

**Comment by MaybeShewill-CV** [comment]
@jonngai Paste the command here. Cannot be such a error if you use the right command:)

**Comment by ManqChen** [comment]
I have the trouble too:
2020-07-16 13:33:07.956566: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at save_restore_v2_ops.cc:184 : Not found: Key LaneNet/bisenetv2_backend/instance_seg/pix_bn/moving_mean not found in checkpoint
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1334, in _do_call
    return fn(*args)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.NotFoundError: Key LaneNet/bisenetv2_backend/instance_seg/pix_bn/moving_mean not found in checkpoint
	 [[{{node save/RestoreV2}} = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2/tensor_names, save/RestoreV2/shape_and_slices)]]

**Comment by ManqChen** [comment]
@MaybeShewill-CV
I have the trouble too:
2020-07-16 13:33:07.956566: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at save_restore_v2_ops.cc:184 : Not found: Key LaneNet/bisenetv2_backend/instance_seg/pix_bn/moving_mean not found in checkpoint
Traceback (most recent call last):
File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1334, in _do_call
return fn(*args)
File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1319, in _run_fn
options, feed_dict, fetch_list, target_list, run_metadata)
File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1407, in _call_tf_sessionrun
run_metadata)
tensorflow.python.framework.errors_impl.NotFoundError: Key LaneNet/bisenetv2_backend/instance_seg/pix_bn/moving_mean not found in checkpoint
[[{{node save/RestoreV2}} = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2/tensor_names, save/RestoreV2/shape_and_slices)]]

**Comment by MaybeShewill-CV** [comment]
@ManqChen Please please please paste your command here. Can not get any useful information from you. How can I help????

**Comment by ManqChen** [comment]
@MaybeShewill-CV Thank you for  responding,I use the command : python3 tools/test_lanenet.py --weights_path ./model/weights/tusimple_lanenet_vgg.ckpt --image_path ./data/tusimple_test_image/0.jpg

**Comment by ManqChen** [comment]
@MaybeShewill-CV  but there is always the problem:NotFoundError (see above for traceback): Restoring from checkpoint failed. This is most likely due to a Variable name or other graph key that is missing from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:

Key LaneNet/bisenetv2_backend/instance_seg/pix_bn/moving_mean not found in checkpoint
	 [[node save/RestoreV2 (defined at tools/test_lanenet.py:122)  = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2/tensor_names, save/RestoreV2/shape_and_slices)]]

**Comment by MaybeShewill-CV** [comment]
@ManqChen vgg based pertained ckpt file was not matched with the code here. Please check readme file carefully and download the new pretrained weights file or you may train the vgg based lancet by yourself. I have delete the old link in readme file do not know how you come to the old pretrained model.

**Comment by ManqChen** [comment]
@MaybeShewill-CV Thank you very much for responding again,I download the new weights files, then ,there is another probelm;

2020-07-16 14:46:51.871243: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
Traceback (most recent call last):
  File "tools/test_lanenet.py", line 175, in <module>
    test_lanenet(args.image_path, args.weights_path)
  File "tools/test_lanenet.py", line 127, in test_lanenet
    saver.restore(sess=sess, save_path=weights_path)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/saver.py", line 1538, in restore
    + compat.as_text(save_path))
ValueError: The passed save_path is not a valid checkpoint: ./model/BiseNetV2_LaneNet_Tusimple_Model_Weights/tusimple_lanenet_vgg.ckpt

**Comment by ManqChen** [comment]
@MaybeShewill-CV  Thank you so much to help me. I  managed to solve the problem

**Comment by MaybeShewill-CV** [comment]
@jonngai Download the right ckpt file the problem won't exist. Besides the weights_path should be something like xxx.ckpt rather than xxx.ckpt.index :)

**Comment by jonngai** [comment]
@MaybeShewill-CV, yup, you are correct. I was pointing it to the actual index rather than the file prefix. It seems to work now. Sorry, I'm pretty new to tensorflow. Thanks for taking the time to respond!
