### ISSUE TITLE
CKPT path issue

### ISSUE THREAD

**Issue by canozcivelek** [MaybeShewill-CV/lanenet-lane-detection#431]
Hi, I downloaded the model from https://www.dropbox.com/sh/0b6r0ljqi76kyg9/AADedYWO3bnx4PhK1BmbJkJKa?dl=0 link and saved it under /model/tusimple_lanenet_vgg/ directory. When I run python tools/test_lanenet.py --weights_path model/tusimple_lanenet_vgg/tusimple_lanenet.ckpt.meta --image_path ./data/tusimple_test_image/0.jpg command, it gives error. And I tried it with each ckpt file, all ending in error.

INFO:tensorflow:Restoring parameters from model/tusimple_lanenet_vgg/tusimple_lanenet.ckpt.meta
I0717 10:58:19.111710 10745 saver.py:1280] Restoring parameters from model/tusimple_lanenet_vgg/tusimple_lanenet.ckpt.meta
2020-07-17 10:58:20.942410: W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open model/tusimple_lanenet_vgg/tusimple_lanenet.ckpt.meta: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
2020-07-17 10:58:20.943990: W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open model/tusimple_lanenet_vgg/tusimple_lanenet.ckpt.meta: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
2020-07-17 10:58:20.944109: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at save_restore_tensor.cc:175 : Data loss: Unable to open table file model/tusimple_lanenet_vgg/tusimple_lanenet.ckpt.meta: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1356, in _do_call
    return fn(*args)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1341, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1429, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.DataLossError: 2 root error(s) found.
  (0) Data loss: Unable to open table file model/tusimple_lanenet_vgg/tusimple_lanenet.ckpt.meta: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
	 [[{{node save/RestoreV2}}]]
  (1) Data loss: Unable to open table file model/tusimple_lanenet_vgg/tusimple_lanenet.ckpt.meta: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
	 [[{{node save/RestoreV2}}]]
	 [[save/RestoreV2/_407]]
0 successful operations.
0 derived errors ignored.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tools/test_lanenet.py", line 158, in <module>
    test_lanenet(args.image_path, args.weights_path)
  File "tools/test_lanenet.py", line 112, in test_lanenet
    saver.restore(sess=sess, save_path=weights_path)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/saver.py", line 1286, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 950, in run
    run_metadata_ptr)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1173, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1350, in _do_run
    run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1370, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.DataLossError: 2 root error(s) found.
  (0) Data loss: Unable to open table file model/tusimple_lanenet_vgg/tusimple_lanenet.ckpt.meta: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
	 [[node save/RestoreV2 (defined at tools/test_lanenet.py:109) ]]
  (1) Data loss: Unable to open table file model/tusimple_lanenet_vgg/tusimple_lanenet.ckpt.meta: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
	 [[node save/RestoreV2 (defined at tools/test_lanenet.py:109) ]]
	 [[save/RestoreV2/_407]]
0 successful operations.
0 derived errors ignored.

Original stack trace for 'save/RestoreV2':
  File "tools/test_lanenet.py", line 158, in <module>
    test_lanenet(args.image_path, args.weights_path)
  File "tools/test_lanenet.py", line 109, in test_lanenet
    saver = tf.train.Saver(variables_to_restore)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/saver.py", line 825, in __init__
    self.build()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/saver.py", line 837, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/saver.py", line 875, in _build
    build_restore=build_restore)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/saver.py", line 508, in _build_internal
    restore_sequentially, reshape)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/saver.py", line 328, in _AddRestoreOps
    restore_sequentially)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/saver.py", line 575, in bulk_restore
    return io_ops.restore_v2(filename_tensor, names, slices, dtypes)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/gen_io_ops.py", line 1696, in restore_v2
    name=name)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 3616, in create_op
    op_def=op_def)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 2005, in __init__
    self._traceback = tf_stack.extract_stack()

**Comment by MaybeShewill-CV** [comment]
@canozcivelek weights path should be xxxx.ckpt rather than xxx.ckpt.meta. Seems you're not familiar with tf. Maybe learn some basic skills will help:)
