### ISSUE TITLE
InvalidArgumentError: Input to reshape is a tensor with 626688 values, but the requested shape has 156672

### ISSUE THREAD

**Issue by iltertaha** [MaybeShewill-CV/lanenet-lane-detection#447]
Hi,
I want to train the lanenet with my own images. 
I have successfully created instance, binary images and tfrecords.
However, when I run the training, I got the following error.

Seems like input dimension error but I've checked both your binary and instance images and mine have same size (720, 1280, 3).
I have only 28 images just to try. And my batch size is 2.

How can I solve this problem? Thanks in advance.

```

2020-09-10 11:35:04.480 | INFO     | trainner.tusimple_lanenet_multi_gpu_trainner:train:397 - => Starts to train LaneNet from scratch ...
  0%|                                                                                                                                                                                | 0/13 [00:04<?, ?it/s]
Traceback (most recent call last):
  File "/home/mypc/anaconda3/envs/lanenet/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1356, in _do_call
    return fn(*args)
  File "/home/mypc/anaconda3/envs/lanenet/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1341, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/mypc/anaconda3/envs/lanenet/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1429, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Input to reshape is a tensor with 626688 values, but the requested shape has 156672
	 [[{{node Reshape_2}}]]
	 [[graph_input_node/train_IteratorGetNext_1]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tools/train_lanenet_tusimple.py", line 46, in <module>
    train_model()
  File "tools/train_lanenet_tusimple.py", line 38, in train_model
    worker.train()
  File "/home/mypc/Desktop/lanenet-lane-detection/trainner/tusimple_lanenet_multi_gpu_trainner.py", line 413, in train
    self._global_step
  File "/home/mypc/anaconda3/envs/lanenet/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 950, in run
    run_metadata_ptr)
  File "/home/mypc/anaconda3/envs/lanenet/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1173, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/mypc/anaconda3/envs/lanenet/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1350, in _do_run
    run_metadata)
  File "/home/mypc/anaconda3/envs/lanenet/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1370, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Input to reshape is a tensor with 626688 values, but the requested shape has 156672
	 [[{{node Reshape_2}}]]
	 [[graph_input_node/train_IteratorGetNext_1]]


```

**Comment by MaybeShewill-CV** [comment]
@iltertaha The input tensor shape of the net was [256, 512]. Some of your code must have done some thing wrong with the tensor shape:)

**Comment by nikhilbv** [comment]
@MaybeShewill-CV I tried to change the `TRAIN_CROP_SIZE` to [768,384] in the config file and got the same error. How to change the input tensor shape in the new net?

**Comment by MaybeShewill-CV** [comment]
@nikhilbv 1.Change config file 2. Regenerate tfrecords file 3.test data feed pip line
