### ISSUE TITLE
Bad Magic Number?

### ISSUE THREAD

**Issue by zoombinis** [MaybeShewill-CV/lanenet-lane-detection#470]
Trying to run this with tensorflow_gpu==1.14.0 as its the required version of my other project and I am getting the below error using the latest model:

```
python tools/test_lanenet.py  --weights_path model/new_model/tusimple_lanenet.ckpt --image_path ./data/tusimple_test_image/0.jpg
```

>2020-11-22 18:01:06.414881: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at save_restore_v2_ops.cc:184 : Data loss: not an sstable (bad magic number)

the model files are:

model/new_model/tusimple_lanenet.ckpt.data-00000-of-00001
model/new_model/tusimple_lanenet.ckpt.index
model/new_model/tusimple_lanenet.ckpt.meta

**Comment by MaybeShewill-CV** [comment]
@zoombinis 1.Do not support python2 2.Tensorflow 1.14 should also works well:)

**Comment by zoombinis** [comment]
I'm trying with python 3.5.10 now. you don't have the requirement versions listed, what version are you using for tensorflow? 2.3.1?

**Comment by zoombinis** [comment]
Hmm even with python 3.5.10 and tensorflow_gpu 1.15.0 I am still getting this error. here is the full output:

>/opt/lanenet/lanenet-lane-detection-master# python tools/test_lanenet.py --weights_path model/tusimple_lanenet.ckpt --image_path ./data/tusimple_test_image/0.jpg 
2020-11-23 04:11:40.360 | INFO     | __main__:test_lanenet:79 - Start reading image and preprocessing
2020-11-23 04:11:40.372 | INFO     | __main__:test_lanenet:85 - Image load complete, cost time: 0.01127s
WARNING:tensorflow:From tools/test_lanenet.py:87: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.
W1123 04:11:40.372748 735 module_wrapper.py:139] From tools/test_lanenet.py:87: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.
WARNING:tensorflow:From /opt/lanenet/lanenet-lane-detection-master/lanenet_model/lanenet.py:45: The name tf.variable_scope is deprecated. Please use tf.compat.v1.variable_scope instead.
W1123 04:11:40.386028 735 module_wrapper.py:139] From /opt/lanenet/lanenet-lane-detection-master/lanenet_model/lanenet.py:45: The name tf.variable_scope is deprecated. Please use tf.compat.v1.variable_scope instead.
WARNING:tensorflow:
The TensorFlow contrib module will not be included in TensorFlow 2.0.For more information, please see:
https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
https://github.com/tensorflow/addons
https://github.com/tensorflow/io (for I/O related ops)
If you depend on functionality not listed there, please file an issue.
W1123 04:11:40.386683 735 lazy_loader.py:50] 
The TensorFlow contrib module will not be included in TensorFlow 2.0.For more information, please see:
https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
https://github.com/tensorflow/addons
https://github.com/tensorflow/io (for I/O related ops)
If you depend on functionality not listed there, please file an issue.
WARNING:tensorflow:From /opt/lanenet/lanenet-lane-detection-master/semantic_segmentation_zoo/cnn_basenet.py:70: The name tf.get_variable is deprecated. Please use tf.compat.v1.get_variable instead.
W1123 04:11:40.641596 735 module_wrapper.py:139] From /opt/lanenet/lanenet-lane-detection-master/semantic_segmentation_zoo/cnn_basenet.py:70: The name tf.get_variable is deprecated. Please use tf.compat.v1.get_variable instead.
WARNING:tensorflow:From /opt/lanenet/lanenet-lane-detection-master/semantic_segmentation_zoo/cnn_basenet.py:352: batch_normalization (from tensorflow.python.layers.normalization) is deprecated and will be removed in a future version.
Instructions for updating:
Use keras.layers.BatchNormalization instead.  In particular, `tf.control_dependencies(tf.GraphKeys.UPDATE_OPS)` should not be used (consult the `tf.keras.layers.batch_normalization` documentation).
W1123 04:11:40.651075 735 deprecation.py:323] From /opt/lanenet/lanenet-lane-detection-master/semantic_segmentation_zoo/cnn_basenet.py:352: batch_normalization (from tensorflow.python.layers.normalization) is deprecated and will be removed in a future version.
Instructions for updating:
Use keras.layers.BatchNormalization instead.  In particular, `tf.control_dependencies(tf.GraphKeys.UPDATE_OPS)` should not be used (consult the `tf.keras.layers.batch_normalization` documentation).
WARNING:tensorflow:From /usr/local/lib/python3.5/dist-packages/tensorflow_core/python/layers/normalization.py:327: Layer.apply (from tensorflow.python.keras.engine.base_layer) is deprecated and will be removed in a future version.
Instructions for updating:
Please use `layer.__call__` method instead.
W1123 04:11:40.651708 735 deprecation.py:323] From /usr/local/lib/python3.5/dist-packages/tensorflow_core/python/layers/normalization.py:327: Layer.apply (from tensorflow.python.keras.engine.base_layer) is deprecated and will be removed in a future version.
Instructions for updating:
Please use `layer.__call__` method instead.
WARNING:tensorflow:From /opt/lanenet/lanenet-lane-detection-master/semantic_segmentation_zoo/cnn_basenet.py:177: The name tf.nn.max_pool is deprecated. Please use tf.nn.max_pool2d instead.
W1123 04:11:40.895126 735 module_wrapper.py:139] From /opt/lanenet/lanenet-lane-detection-master/semantic_segmentation_zoo/cnn_basenet.py:177: The name tf.nn.max_pool is deprecated. Please use tf.nn.max_pool2d instead.
WARNING:tensorflow:From /opt/lanenet/lanenet-lane-detection-master/semantic_segmentation_zoo/cnn_basenet.py:201: The name tf.nn.avg_pool is deprecated. Please use tf.nn.avg_pool2d instead.
W1123 04:11:41.847226 735 module_wrapper.py:139] From /opt/lanenet/lanenet-lane-detection-master/semantic_segmentation_zoo/cnn_basenet.py:201: The name tf.nn.avg_pool is deprecated. Please use tf.nn.avg_pool2d instead.
WARNING:tensorflow:From /opt/lanenet/lanenet-lane-detection-master/semantic_segmentation_zoo/bisenet_v2.py:584: The name tf.image.resize_bilinear is deprecated. Please use tf.compat.v1.image.resize_bilinear instead.
W1123 04:11:41.903072 735 module_wrapper.py:139] From /opt/lanenet/lanenet-lane-detection-master/semantic_segmentation_zoo/bisenet_v2.py:584: The name tf.image.resize_bilinear is deprecated. Please use tf.compat.v1.image.resize_bilinear instead.
WARNING:tensorflow:From tools/test_lanenet.py:95: The name tf.ConfigProto is deprecated. Please use tf.compat.v1.ConfigProto instead.
W1123 04:11:42.220115 735 module_wrapper.py:139] From tools/test_lanenet.py:95: The name tf.ConfigProto is deprecated. Please use tf.compat.v1.ConfigProto instead.
WARNING:tensorflow:From tools/test_lanenet.py:100: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.
W1123 04:11:42.220432 735 module_wrapper.py:139] From tools/test_lanenet.py:100: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.
2020-11-23 04:11:42.220968: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-11-23 04:11:42.247023: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2599990000 Hz
2020-11-23 04:11:42.247569: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55ee54b96200 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-11-23 04:11:42.247586: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-11-23 04:11:42.249029: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2020-11-23 04:11:42.345690: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:983] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-11-23 04:11:42.346058: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55ee55619160 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2020-11-23 04:11:42.346075: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Quadro RTX 3000, Compute Capability 7.5
2020-11-23 04:11:42.346198: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:983] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-11-23 04:11:42.346494: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: Quadro RTX 3000 major: 7 minor: 5 memoryClockRate(GHz): 1.38
pciBusID: 0000:01:00.0
2020-11-23 04:11:42.346710: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcudart.so.10.0'; dlerror: libcudart.so.10.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda/compat/lib:/usr/local/nvidia/lib:/usr/local/nvidia/lib64
2020-11-23 04:11:42.346876: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcublas.so.10.0'; dlerror: libcublas.so.10.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda/compat/lib:/usr/local/nvidia/lib:/usr/local/nvidia/lib64
2020-11-23 04:11:42.347014: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcufft.so.10.0'; dlerror: libcufft.so.10.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda/compat/lib:/usr/local/nvidia/lib:/usr/local/nvidia/lib64
2020-11-23 04:11:42.347226: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcurand.so.10.0'; dlerror: libcurand.so.10.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda/compat/lib:/usr/local/nvidia/lib:/usr/local/nvidia/lib64
2020-11-23 04:11:42.347437: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcusolver.so.10.0'; dlerror: libcusolver.so.10.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda/compat/lib:/usr/local/nvidia/lib:/usr/local/nvidia/lib64
2020-11-23 04:11:42.347594: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcusparse.so.10.0'; dlerror: libcusparse.so.10.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda/compat/lib:/usr/local/nvidia/lib:/usr/local/nvidia/lib64
2020-11-23 04:11:42.393851: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-11-23 04:11:42.393889: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1641] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
2020-11-23 04:11:42.393908: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-11-23 04:11:42.393915: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0 
2020-11-23 04:11:42.393922: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N 
WARNING:tensorflow:From tools/test_lanenet.py:109: The name tf.train.Saver is deprecated. Please use tf.compat.v1.train.Saver instead.
W1123 04:11:42.396784 735 module_wrapper.py:139] From tools/test_lanenet.py:109: The name tf.train.Saver is deprecated. Please use tf.compat.v1.train.Saver instead.
INFO:tensorflow:Restoring parameters from model/tusimple_lanenet.ckpt
I1123 04:11:42.620656 735 saver.py:1284] Restoring parameters from model/tusimple_lanenet.ckpt
2020-11-23 04:11:42.838051: W tensorflow/core/framework/op_kernel.cc:1651] OP_REQUIRES failed at save_restore_v2_ops.cc:184 : Data loss: not an sstable (bad magic number)
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow_core/python/client/session.py", line 1365, in _do_call
    return fn(*args)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow_core/python/client/session.py", line 1350, in _run_fn
    target_list, run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow_core/python/client/session.py", line 1443, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.DataLossError: not an sstable (bad magic number)
         [[{{node save/RestoreV2}}]]
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "tools/test_lanenet.py", line 158, in <module>
    test_lanenet(args.image_path, args.weights_path)
  File "tools/test_lanenet.py", line 112, in test_lanenet
    saver.restore(sess=sess, save_path=weights_path)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow_core/python/training/saver.py", line 1290, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/usr/local/lib/python3.5/dist-packages/tensorflow_core/python/client/session.py", line 956, in run
    run_metadata_ptr)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow_core/python/client/session.py", line 1180, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow_core/python/client/session.py", line 1359, in _do_run
    run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow_core/python/client/session.py", line 1384, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.DataLossError: not an sstable (bad magic number)
         [[node save/RestoreV2 (defined at /usr/local/lib/python3.5/dist-packages/tensorflow_core/python/framework/ops.py:1748) ]]
Original stack trace for 'save/RestoreV2':
  File "tools/test_lanenet.py", line 158, in <module>
    test_lanenet(args.image_path, args.weights_path)
  File "tools/test_lanenet.py", line 109, in test_lanenet
    saver = tf.train.Saver(variables_to_restore)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow_core/python/training/saver.py", line 828, in __init__
    self.build()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow_core/python/training/saver.py", line 840, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow_core/python/training/saver.py", line 878, in _build
    build_restore=build_restore)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow_core/python/training/saver.py", line 508, in _build_internal
    restore_sequentially, reshape)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow_core/python/training/saver.py", line 328, in _AddRestoreOps
    restore_sequentially)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow_core/python/training/saver.py", line 575, in bulk_restore
    return io_ops.restore_v2(filename_tensor, names, slices, dtypes)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow_core/python/ops/gen_io_ops.py", line 1696, in restore_v2
    name=name)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow_core/python/framework/op_def_library.py", line 794, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow_core/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow_core/python/framework/ops.py", line 3357, in create_op
    attrs, op_def, compute_device)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow_core/python/framework/ops.py", line 3426, in _create_op_internal
    op_def=op_def)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow_core/python/framework/ops.py", line 1748, in __init__
    self._traceback = tf_stack.extract_stack()

**Comment by zoombinis** [comment]
I think I need to upgrade tensorflow to 2.3.1 in order to support Cuda 10.2 based on some of the error messages above. Does that sound right?

**Comment by zoombinis** [comment]
@MaybeShewill-CV I think I need to upgrade tensorflow to 2.3.1 in order to support Cuda 10.2 based on some of the error messages above. Does that sound right?

**Comment by MaybeShewill-CV** [comment]
@zoombinis That's a problem relative to tensorflow you may get satisfied answer there. By the way I use tensorflow 1.15 and this project works well:)

**Comment by zoombinis** [comment]
@MaybeShewill-CV thanks I've resolved those errors, but still getting this magic number issue.

I am using python2 with tensorflow 1.14.0

I think python2 isnt the issue.. are these still GPU/tensorflow related issues you think?

>WARNING:tensorflow:Entity <bound method BatchNormalization.call of <tensorflow.python.layers.normalization.BatchNormalization object at 0x7f56ad243590>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method BatchNormalization.call of <tensorflow.python.layers.normalization.BatchNormalization object at 0x7f56ad243590>>: AssertionError: Bad argument number for Name: 3, expecting 4
...
2020-11-23 19:03:47.100373: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1326] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 5341 MB memory) -> physical GPU (device: 0, name: Quadro RTX 3000, pci bus id: 0000:01:00.0, compute capability: 7.5)
WARNING:tensorflow:From tools/test_lanenet.py:109: The name tf.train.Saver is deprecated. Please use tf.compat.v1.train.Saver instead
W1123 19:03:47.102619 560 deprecation_wrapper.py:119] From tools/test_lanenet.py:109: The name tf.train.Saver is deprecated. Please use tf.compat.v1.train.Saver instead.
WARNING:tensorflow:From /usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py:1276: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
W1123 19:03:47.246346 560 deprecation.py:323] From /usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py:1276: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
INFO:tensorflow:Restoring parameters from /opt/lanenet-lane-detection-master/tools/model/tusimple_lanenet.ckpt
I1123 19:03:47.247122 560 saver.py:1280] Restoring parameters from /opt/lanenet-lane-detection-master/tools/model/tusimple_lanenet.ckpt
2020-11-23 19:03:47.499821: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at save_restore_v2_ops.cc:184 : Data loss: not an sstable (bad magic number)
Traceback (most recent call last):
  File "tools/test_lanenet.py", line 158, in <module>

**Comment by zoombinis** [comment]
Just tried with python 3.5 and tensorflow 1.14.0.. same issue... What version of Cuda do you run this on?

>2020-11-23 19:37:35.137824: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1326] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 5341 MB memory) -> physical GPU (device: 0, name: Quadro RTX 3000, pci bus id: 0000:01:00.0, compute capability: 7.5)
WARNING:tensorflow:From tools/test_lanenet.py:109: The name tf.train.Saver is deprecated. Please use tf.compat.v1.train.Saver instead.
W1123 19:37:35.140415 3727 deprecation_wrapper.py:119] From tools/test_lanenet.py:109: The name tf.train.Saver is deprecated. Please use tf.compat.v1.train.Saver instead.
WARNING:tensorflow:From /usr/local/lib/python3.5/dist-packages/tensorflow/python/training/saver.py:1276: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
W1123 19:37:35.301486 3727 deprecation.py:323] From /usr/local/lib/python3.5/dist-packages/tensorflow/python/training/saver.py:1276: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
INFO:tensorflow:Restoring parameters from /opt/lanenet-lane-detection-master/tools/model/tusimple_lanenet.ckpt
I1123 19:37:35.302382 3727 saver.py:1280] Restoring parameters from /opt/lanenet-lane-detection-master/tools/model/tusimple_lanenet.ckpt
2020-11-23 19:37:35.547303: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at save_restore_v2_ops.cc:184 : Data loss: not an sstable (bad magic number)
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1356, in _do_call
    return fn(*args)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1341, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1429, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.DataLossError: 2 root error(s) found.
  (0) Data loss: not an sstable (bad magic number)
         [[{{node save/RestoreV2}}]]
  (1) Data loss: not an sstable (bad magic number)
         [[{{node save/RestoreV2}}]]
         [[save/RestoreV2/_549]]
0 successful operations.
0 derived errors ignored.

**Comment by zoombinis** [comment]
@MaybeShewill-CV how unfotunate! It appears the download links I was using are not permanent and expired! 

So let it be known this works on Python2 with tensorflow 1.14.0 (last supported V1 python2 tensorflow version)

Now I just have other fun issues to fix ;)

> 2020-11-23 20:09:07.408758: E tensorflow/stream_executor/cuda/cuda_driver.cc:828] failed to allocate 4.00G (4294967296 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory

**Comment by MaybeShewill-CV** [comment]
@zoombinis Wish you good luck:)
