### ISSUE TITLE
Got Problem in testing on google colab

### ISSUE THREAD

**Issue by sabih411** [MaybeShewill-CV/lanenet-lane-detection#484]
**Input command**
!python3 tools/test_lanenet.py  --weights_path model/tusimple_lanenet/checkpoint   --image_path data/tusimple_test_image/0.jpg

**Output**

2021-01-26 11:46:29.920382: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.10.1
WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/tensorflow/python/compat/v2_compat.py:96: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
2021-01-26 11:46:31.861 | INFO     | __main__:test_lanenet:80 - Start reading image and preprocessing
2021-01-26 11:46:31.879 | INFO     | __main__:test_lanenet:86 - Image load complete, cost time: 0.01741s
Traceback (most recent call last):
  File "tools/test_lanenet.py", line 159, in <module>
    test_lanenet(args.image_path, args.weights_path)
  File "tools/test_lanenet.py", line 91, in test_lanenet
    binary_seg_ret, instance_seg_ret = net.inference(input_tensor=input_tensor, name='LaneNet')
  File "/content/lanenet-lane-detection/lanenet_model/lanenet.py", line 51, in inference
    reuse=reuse
  File "/content/lanenet-lane-detection/lanenet_model/lanenet_front_end.py", line 46, in build_model
    reuse=reuse
  File "/content/lanenet-lane-detection/semantic_segmentation_zoo/bisenet_v2.py", line 1056, in build_model
    name='detail_branch'
  File "/content/lanenet-lane-detection/semantic_segmentation_zoo/bisenet_v2.py", line 881, in build_detail_branch
    need_activate=True
  File "/content/lanenet-lane-detection/semantic_segmentation_zoo/bisenet_v2.py", line 832, in _conv_block
    name='conv'
  File "/content/lanenet-lane-detection/semantic_segmentation_zoo/cnn_basenet.py", line 70, in conv2d
    w = tf.compat.v1.get_variable('W', filter_shape, initializer=w_init)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/variable_scope.py", line 1593, in get_variable
    aggregation=aggregation)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/variable_scope.py", line 1336, in get_variable
    aggregation=aggregation)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/variable_scope.py", line 591, in get_variable
    aggregation=aggregation)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/variable_scope.py", line 543, in _true_getter
    aggregation=aggregation)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/variable_scope.py", line 874, in _get_single_variable
    shape = tensor_shape.as_shape(shape)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/tensor_shape.py", line 1235, in as_shape
    return TensorShape(shape)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/tensor_shape.py", line 758, in __init__
    self._dims = [Dimension(d) for d in dims]
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/tensor_shape.py", line 758, in <listcomp>
    self._dims = [Dimension(d) for d in dims]
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/tensor_shape.py", line 206, in __init__
    .format(value, type(value))), None)
  File "<string>", line 3, in raise_from
TypeError: Dimension value must be integer or None or have an __index__ method, got value '3.0' with type '<class 'float'>'

**Comment by MaybeShewill-CV** [comment]
@sabih411 Wrong checkpoint path was supplied here. Google how to use tf checkpoint file to restore the model:)

**Comment by sabih411** [comment]
@MaybeShewill-CV Yes I'm considering that but the weight folder provided in the readme instruction had 4 file in it and I tried addressing them all individually but the output would still stand the same.
