### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfd in position 0: invalid start byte

### ISSUE THREAD

**Issue by edwardchang0112** [MaybeShewill-CV/lanenet-lane-detection#510]
On my NVIDIA jetson NX...

• JetPack Version (valid for Jetson only)
4.5-b129

• TensorRT Version
7.1.3

By running
```
python3 tools/test_lanenet.py --weights_path model/tusimple_lanenet/tusimple_lanenet.ckpt --image_path data/tusimple_test_image/0.jpg
```
get 
```
2021-06-25 04:05:06.716212: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.10.2
WARNING:tensorflow:Deprecation warnings have been disabled. Set TF_ENABLE_DEPRECATION_WARNINGS=1 to re-enable them.
Traceback (most recent call last):
  File "tools/test_lanenet.py", line 19, in <module>
    import tensorflow as tf
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/__init__.py", line 101, in <module>
    from tensorflow_core import *
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/__init__.py", line 36, in <module>
    from tensorflow._api.v1 import compat
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/_api/v1/compat/__init__.py", line 23, in <module>
    from tensorflow._api.v1.compat import v1
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/_api/v1/compat/v1/__init__.py", line 673, in <module>
    from tensorflow_estimator.python.estimator.api._v1 import estimator
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/__init__.py", line 10, in <module>
    from tensorflow_estimator._api.v1 import estimator
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/_api/v1/estimator/__init__.py", line 12, in <module>
    from tensorflow_estimator._api.v1.estimator import inputs
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/_api/v1/estimator/inputs/__init__.py", line 10, in <module>
    from tensorflow_estimator.python.estimator.inputs.numpy_io import numpy_input_fn
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/inputs/numpy_io.py", line 26, in <module>
    from tensorflow_estimator.python.estimator.inputs.queues import feeding_functions
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/inputs/queues/feeding_functions.py", line 40, in <module>
    import pandas as pd
  File "/usr/lib/python3/dist-packages/pandas/__init__.py", line 58, in <module>
    from pandas.io.api import *
  File "/usr/lib/python3/dist-packages/pandas/io/api.py", line 19, in <module>
    from pandas.io.packers import read_msgpack, to_msgpack
  File "/usr/lib/python3/dist-packages/pandas/io/packers.py", line 68, in <module>
    from pandas.util._move import (
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfd in position 0: invalid start byte

```
Anyone got this issue? Please share some comments with me!

**Comment by MaybeShewill-CV** [comment]
@edwardchang0112 try tensorflow-gpu 1.15:)

**Comment by edwardchang0112** [comment]
@MaybeShewill-CV 

Following NVIDIA's Doc (https://docs.nvidia.com/deeplearning/frameworks/install-tf-jetson-platform/index.html). For my tensorflow is as follow. 

>>> tf.__version__
'1.15.5'

is this fine for this project? Since for jetson, is that possible to install the specific 'tensorflow-gpu 1.15'?

**Comment by MaybeShewill-CV** [comment]
@edwardchang0112 I'm not sure for that. Have not tested on Jetson platform :)

**Comment by edwardchang0112** [comment]
@MaybeShewill-CV 

I see. Since I've seen someone tested this project on jetson platform (https://github.com/MaybeShewill-CV/lanenet-lane-detection/issues/383), try to have some advice here.
