### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by GunGoo** [MaybeShewill-CV/lanenet-lane-detection#511]
Hello, I am trying to follow the instruction in your README.  And having the following issue in test_lanenet.py

2021-06-25 11:25:46.777 | INFO     | __main__:test_lanenet:138 - Single imgae inference cost time: 1.97485s
E0625 11:25:46.788245 23860 lanenet_postprocess.py:168] Found array with 0 sample(s) (shape=(0, 4)) while a minimum of 1 is required by StandardScaler.
Traceback (most recent call last):
  File "tools/test_lanenet.py", line 175, in <module>
    test_lanenet(args.image_path, args.weights_path)
  File "tools/test_lanenet.py", line 155, in test_lanenet
    plt.imshow(mask_image[:, :, (2, 1, 0)])
TypeError: 'NoneType' object is not subscriptable

Any suggestions?
Thanks in advance

**Comment by MaybeShewill-CV** [comment]
@GunGoo mask image is None here:)
