### ISSUE TITLE
Is the pre-training file does not match the model?

### ISSUE THREAD

**Issue by AllenZYJ** [MaybeShewill-CV/lanenet-lane-detection#527]
hi, thanks for your awsome work for lane detection, i try to git clone this repo and try to run it , i get the error, the info here:
# 1.my command : 
python3 tools/test_lanenet.py --weights_path lane_model/checkpoint --image_path ./data/tusimple_test_image/0.jpg
# 2.output:
Traceback (most recent call last):
  File "tools/test_lanenet.py", line 158, in <module>
    test_lanenet(args.image_path, args.weights_path)
  File "tools/test_lanenet.py", line 112, in test_lanenet
    saver.restore(sess=sess, save_path=weights_path)
  File "/root/miniconda3/envs/lane/lib/python3.7/site-packages/tensorflow_core/python/training/saver.py", line 1290, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/root/miniconda3/envs/lane/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 956, in run
    run_metadata_ptr)
  File "/root/miniconda3/envs/lane/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1180, in _run
    feed_dict_tensor, options, run_metadata)
  File "/root/miniconda3/envs/lane/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1359, in _do_run
    run_metadata)
  File "/root/miniconda3/envs/lane/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1384, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.DataLossError: Unable to open table file lane_model/checkpoint: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
	 [[node save/RestoreV2 (defined at /root/miniconda3/envs/lane/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py:1748) ]]

Original stack trace for 'save/RestoreV2':
  File "tools/test_lanenet.py", line 158, in <module>
    test_lanenet(args.image_path, args.weights_path)
  File "tools/test_lanenet.py", line 109, in test_lanenet
    saver = tf.train.Saver(variables_to_restore)
  File "/root/miniconda3/envs/lane/lib/python3.7/site-packages/tensorflow_core/python/training/saver.py", line 828, in __init__
    self.build()
  File "/root/miniconda3/envs/lane/lib/python3.7/site-packages/tensorflow_core/python/training/saver.py", line 840, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/root/miniconda3/envs/lane/lib/python3.7/site-packages/tensorflow_core/python/training/saver.py", line 878, in _build
    build_restore=build_restore)
  File "/root/miniconda3/envs/lane/lib/python3.7/site-packages/tensorflow_core/python/training/saver.py", line 508, in _build_internal
    restore_sequentially, reshape)
  File "/root/miniconda3/envs/lane/lib/python3.7/site-packages/tensorflow_core/python/training/saver.py", line 328, in _AddRestoreOps
    restore_sequentially)
  File "/root/miniconda3/envs/lane/lib/python3.7/site-packages/tensorflow_core/python/training/saver.py", line 575, in bulk_restore
    return io_ops.restore_v2(filename_tensor, names, slices, dtypes)
  File "/root/miniconda3/envs/lane/lib/python3.7/site-packages/tensorflow_core/python/ops/gen_io_ops.py", line 1696, in restore_v2
    name=name)
  File "/root/miniconda3/envs/lane/lib/python3.7/site-packages/tensorflow_core/python/framework/op_def_library.py", line 794, in _apply_op_helper
    op_def=op_def)
  File "/root/miniconda3/envs/lane/lib/python3.7/site-packages/tensorflow_core/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/root/miniconda3/envs/lane/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 3357, in create_op
    attrs, op_def, compute_device)
  File "/root/miniconda3/envs/lane/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 3426, in _create_op_internal
    op_def=op_def)
  File "/root/miniconda3/envs/lane/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 1748, in __init__
    self._traceback = tf_stack.extract_stack()
thanks again.

**Comment by MaybeShewill-CV** [comment]
@AllenZYJ The model file path argument should be like xxx.ckpt which you can download via dropbox and I have pasted the url in readme file. You may baidu how to restore a ckpt model using tf.

**Comment by AllenZYJ** [comment]
> @AllenZYJ The model file path argument should be like xxx.ckpt which you can download via dropbox and I have pasted the url in readme file. You may baidu how to restore a ckpt model using tf.
i got the idea , but got the new error like this:
ValueError: The passed save_path is not a valid checkpoint: model/
i do not know why, the model file path is right but the restore() cause the error ,I rarely use tf..,if i should edit the checkpoint file?
thanks for reply

**Comment by MaybeShewill-CV** [comment]
@AllenZYJ Still wrong ckpt file path was uesed here. You need to google how to restore model from ckpt file using tf first:)

**Comment by AllenZYJ** [comment]
> @AllenZYJ Still wrong ckpt file path was uesed here. You need to google how to restore model from ckpt file using tf first:)

thanku again

**Comment by k-nayak** [comment]
> > @AllenZYJ Still wrong ckpt file path was uesed here. You need to google how to restore model from ckpt file using tf first:)
> 
> thanku again

Hello @AllenZYJ and @MaybeShewill-CV  I have been trying to restore the model from the ckpt file but i still face the same error. I have used these methods, https://cv-tricks.com/tensorflow-tutorial/save-restore-tensorflow-models-quick-complete-tutorial/ I see that you have solved the issue. Could you please elaborate on what the steps are or if i am missing something. Thank you in advance.
