### ISSUE TITLE
ValueError: Source image data is not complete, please check if one of the image folder does not exist

### ISSUE THREAD

**Issue by hjh20888** [MaybeShewill-CV/lanenet-lane-detection#552]
Traceback (most recent call last):
  File "D:/PyCharmProjects/lanenet-lane-detection-initial/lanenet-lane-detection-master/tools/make_tusimple_tfrecords.py", line 33, in <module>
    generate_tfrecords()
  File "D:/PyCharmProjects/lanenet-lane-detection-initial/lanenet-lane-detection-master/tools/make_tusimple_tfrecords.py", line 23, in generate_tfrecords
    producer = lanenet_data_feed_pipline.LaneNetDataProducer()
  File "D:\PyCharmProjects\lanenet-lane-detection-initial\lanenet-lane-detection-master\data_provider\lanenet_data_feed_pipline.py", line 50, in __init__
    raise ValueError('Source image data is not complete, '
ValueError: Source image data is not complete, please check if one of the image folder does not exist

**Comment by hjh20888** [comment]
数据集文件名称 gt_binary_image ，gt_instance_image ，image ，val.txt ，train.txt 依旧报错

**Comment by MaybeShewill-CV** [comment]
@hjh20888 查看下代码 D:\PyCharmProjects\lanenet-lane-detection-initial\lanenet-lane-detection-master\data_provider\lanenet_data_feed_pipline.py", line 50 附近。你的数据集不完备 缺文件。具体缺什么你可以查看下代码检查了哪些文件哈:)

**Comment by frozenbird07** [comment]
我也遇到了同样问题，数据集要怎么放进文件夹里？
