### ISSUE TITLE
Training Issue!! Please help

### ISSUE THREAD

**Issue by pankaj251003** [MaybeShewill-CV/lanenet-lane-detection#567]
run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: {{function_node __inference_Dataset_map_decode_236}} Input to reshape is a tensor with 470016 values, but the requested shape has 156672
         [[{{node Reshape_1}}]]
         [[graph_input_node/train_IteratorGetNext_1]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train_lanenet_tusimple.py", line 40, in <module>
    train_model()
  File "train_lanenet_tusimple.py", line 32, in train_model
    worker.train()
  File "C:\Users\admin\Documents\lanenet-lane-detection-master\lanenet-lane-detection-master\lanenet-lane-detection-master\tools\trainner\tusimple_lanenet_multi_gpu_trainner.py", line 409, in train
    train_step_instance_loss, global_step_val = self._sess.run(fetches=[self._train_op, self._miou_update_op, self._write_summary_op_with_miou,self._loss, self._binary_loss, self._instance_loss,self._global_step]
  File "C:\Users\admin\.conda\envs\Lanenet\lib\site-packages\tensorflow_core\python\client\session.py", line 956, in run
    run_metadata_ptr)
  File "C:\Users\admin\.conda\envs\Lanenet\lib\site-packages\tensorflow_core\python\client\session.py", line 1180, in _run
    feed_dict_tensor, options, run_metadata)
  File "C:\Users\admin\.conda\envs\Lanenet\lib\site-packages\tensorflow_core\python\client\session.py", line 1359, in _do_run
    run_metadata)
  File "C:\Users\admin\.conda\envs\Lanenet\lib\site-packages\tensorflow_core\python\client\session.py", line 1384, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError:  Input to reshape is a tensor with 470016 values, but the requested shape has 156672
         [[{{node Reshape_1}}]]
         [[graph_input_node/train_IteratorGetNext_1]]

I have checked input image dimension of all the three folder has 1280x720....please help

**Comment by pankaj251003** [comment]
Solved

**Comment by yousef-sbeih** [comment]
> 156672

can you explain how did you solve it ?
