### ISSUE TITLE
testing error

### ISSUE THREAD

**Issue by ZackySun** [MaybeShewill-CV/lanenet-lane-detection#584]
2023-08-22 22:36:19.798 | INFO     | __main__:test_lanenet:127 - Single imgae inference cost time: 0.00926s
2023-08-22 22:36:19.798 | ERROR    | lanenet_model.lanenet_postprocess:_embedding_feats_dbscan_cluster:170 - Found array with 0 sample(s)
 (shape=(0, 4)) while a minimum of 1 is required by StandardScaler.
Traceback (most recent call last):
  File "tools/test_lanenet.py", line 169, in <module>
    test_lanenet(args.image_path, args.weights_path, with_lane_fit=args.with_lane_fit)
  File "tools/test_lanenet.py", line 139, in test_lanenet
    LOG.info('Model have fitted {:d} lanes'.format(len(lane_params)))
TypeError: object of type 'NoneType' has no len()

**Comment by ZackySun** [comment]
完整的报错是：
PS E:\lanenet-lane-detection> python tools/test_lanenet.py --weights_path ./model/tusimple_lanenet/tusimple_lanenet.ckpt --image_path ./d
ata/tusimple_test_image/2.jpg                  
X:\Anaconda\envs\tfgpu112\lib\site-packages\tensorflow\python\framework\dtypes.py:523: FutureWarning: Passing (type, 1) or '1type' as a s
ynonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
X:\Anaconda\envs\tfgpu112\lib\site-packages\tensorflow\python\framework\dtypes.py:524: FutureWarning: Passing (type, 1) or '1type' as a s
ynonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
X:\Anaconda\envs\tfgpu112\lib\site-packages\tensorflow\python\framework\dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a s
ynonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
X:\Anaconda\envs\tfgpu112\lib\site-packages\tensorflow\python\framework\dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a s
ynonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
X:\Anaconda\envs\tfgpu112\lib\site-packages\tensorflow\python\framework\dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a s
ynonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
X:\Anaconda\envs\tfgpu112\lib\site-packages\tensorflow\python\framework\dtypes.py:532: FutureWarning: Passing (type, 1) or '1type' as a s
ynonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
2023-08-22 22:40:02.198 | INFO     | __main__:test_lanenet:83 - Start reading image and preprocessing
2023-08-22 22:40:02.198 | INFO     | __main__:test_lanenet:89 - Image load complete, cost time: 0.00000s
2023-08-22 22:40:05.636406: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow bina
ry was not compiled to use: AVX2
2023-08-22 22:40:05.758038: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1432] Found device 0 with properties: 
name: NVIDIA GeForce RTX 3070 Laptop GPU major: 8 minor: 6 memoryClockRate(GHz): 1.56
pciBusID: 0000:01:00.0
totalMemory: 8.00GiB freeMemory: 6.96GiB
2023-08-22 22:40:05.758341: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1511] Adding visible gpu devices: 0
2023-08-22 22:40:06.325996: I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] Device interconnect StreamExecutor with strength 1 ed
ge matrix:
2023-08-22 22:40:06.326164: I tensorflow/core/common_runtime/gpu/gpu_device.cc:988]      0 
2023-08-22 22:40:06.326246: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1001] 0:   N
2023-08-22 22:40:06.326427: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/
task:0/device:GPU:0 with 7372 MB memory) -> physical GPU (device: 0, name: NVIDIA GeForce RTX 3070 Laptop GPU, pci bus id: 0000:01:00.0, 
compute capability: 8.6)
2023-08-22 22:40:11.243 | INFO     | __main__:test_lanenet:127 - Single imgae inference cost time: 0.00919s
2023-08-22 22:40:11.258 | ERROR    | lanenet_model.lanenet_postprocess:_embedding_feats_dbscan_cluster:170 - Found array with 0 sample(s)
 (shape=(0, 4)) while a minimum of 1 is required by StandardScaler.
Traceback (most recent call last):
  File "tools/test_lanenet.py", line 169, in <module>
    test_lanenet(args.image_path, args.weights_path, with_lane_fit=args.with_lane_fit)
  File "tools/test_lanenet.py", line 139, in test_lanenet
    LOG.info('Model have fitted {:d} lanes'.format(len(lane_params)))
TypeError: object of type 'NoneType' has no len()

**Comment by EricLyn77** [comment]
Hi, I met this problem as well, may I ask you how to solve this problem?

**Comment by Xu-jianyi** [comment]
i, I met this problem as well, may I ask you how to solve this problem?

**Comment by Darkrred** [comment]
Hi, I met this problem as well, may I ask you how to solve this problem?

**Comment by bbshdh56** [comment]
Hi, I met this problem as well, may I ask you how to solve this problem?
