### ISSUE TITLE
使用dareset数据集里边的lanenet_hnet_data_processor.py报错啊

### ISSUE THREAD

**Issue by baihualinxin** [MaybeShewill-CV/lanenet-lane-detection#59]
改了 
    json_file_list = glob.glob('{:s}/*.json'.format('G:/dareset/dareset/label_data_0313.json'
                                                    'G:/dareset/training'))
两个路径
python 3.6
tensorflow 1.8.0
  File "G:/lanenet-lane-detection/dareset/dareset/lanenet_hnet_data_processor.py", line 93, in _random_dataset
    random_idx = np.random.permutation(self._label_image_path.shape[0])

  File "mtrand.pyx", line 4907, in mtrand.RandomState.permutation

  File "mtrand.pyx", line 4841, in mtrand.RandomState.shuffle

RecursionError: maximum recursion depth exceeded in comparison

**Comment by baihualinxin** [comment]
@MaybeShewill-CV 数据集怎么制作啊

**Comment by MaybeShewill-CV** [comment]
@baihualinxin 数据集问题可以去查看tusimple lane的官网,有详细说明

**Comment by baihualinxin** [comment]
@MaybeShewill-CV 报这样的错是什么原因造成的
 I0913 16:35:19.797681 13236 train_lanenet.py:163] Training from scratch
Traceback (most recent call last):
  File "tools/train_lanenet.py", line 308, in <module>
    train_net(args.dataset_dir, args.weights_path, net_flag=args.net)
  File "tools/train_lanenet.py", line 191, in train_net
    gt_imgs, binary_gt_labels, instance_gt_labels = train_dataset.next_batch(CFG.TRAIN.BATCH_SIZE)
  File "G:\lanenet-lane-detection-master\data_provider\lanenet_data_processor.py", line 95, in next_batch
    return self.next_batch(batch_size)
  File "G:\lanenet-lane-detection-master\data_provider\lanenet_data_processor.py", line 95, in next_batch
    return self.next_batch(batch_size)
  File "G:\lanenet-lane-detection-master\data_provider\lanenet_data_processor.py", line 95, in next_batch
    return self.next_batch(batch_size)
  [Previous line repeated 987 more times]
  File "G:\lanenet-lane-detection-master\data_provider\lanenet_data_processor.py", line 93, in next_batch
    self._random_dataset()
  File "G:\lanenet-lane-detection-master\data_provider\lanenet_data_processor.py", line 66, in _random_dataset
    random_idx = np.random.permutation(len(self._gt_img_list))
  File "mtrand.pyx", line 4907, in mtrand.RandomState.permutation
  File "mtrand.pyx", line 4824, in mtrand.RandomState.shuffle
  File "D:\Anaconda3\envs\tensorflow-gpu1\lib\site-packages\numpy\core\_internal.py", line 254, in __init__
    if self._arr.ndim == 0:
RecursionError: maximum recursion depth exceeded in comparison

**Comment by MaybeShewill-CV** [comment]
@baihualinxin 需要知道你训练数据集是按照readme文件结构构造的么

**Comment by MaybeShewill-CV** [comment]
@baihualinxin 我说的意思是文件组织结构

**Comment by baihualinxin** [comment]
@MaybeShewill-CV 需要什么文件组织结构没懂

**Comment by baihualinxin** [comment]
```
{
  "lanes": [
        [-2, -2, -2, -2, 632, 625, 617, 609, 601, 594, 586, 578, 570, 563, 555, 547, 539, 532, 524, 516, 508, 501, 493, 485, 477, 469, 462, 454, 446, 438, 431, 423, 415, 407, 400, 392, 384, 376, 369, 361, 353, 345, 338, 330, 322, 314, 307, 299],
        [-2, -2, -2, -2, 719, 734, 748, 762, 777, 791, 805, 820, 834, 848, 863, 877, 891, 906, 920, 934, 949, 963, 978, 992, 1006, 1021, 1035, 1049, 1064, 1078, 1092, 1107, 1121, 1135, 1150, 1164, 1178, 1193, 1207, 1221, 1236, 1250, 1265, -2, -2, -2, -2, -2],
        [-2, -2, -2, -2, -2, 532, 503, 474, 445, 416, 387, 358, 329, 300, 271, 241, 212, 183, 154, 125, 96, 67, 38, 9, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2],
        [-2, -2, -2, 781, 822, 862, 903, 944, 984, 1025, 1066, 1107, 1147, 1188, 1229, 1269, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2]
       ],
  "h_samples": [240, 250, 260, 270, 280, 290, 300, 310, 320, 330, 340, 350, 360, 370, 380, 390, 400, 410, 420, 430, 440, 450, 460, 470, 480, 490, 500, 510, 520, 530, 540, 550, 560, 570, 580, 590, 600, 610, 620, 630, 640, 650, 660, 670, 680, 690, 700, 710],
  "raw_file": "path_to_clip"
}
```

-2的不要 。lanes 取出一组。。第一组数据取一个，跟h_samples第一个组合。这样的
raw_file 图片的路径和名称

**Comment by MaybeShewill-CV** [comment]
@baihualinxin 类似这样的文件结构
![screenshot from 2018-09-13 18-05-01](https://user-images.githubusercontent.com/15725187/45482038-9696e080-b77f-11e8-9c48-1cf0397b2e1c.png)

**Comment by baihualinxin** [comment]
@MaybeShewill-CV  没有问题是这样的

**Comment by baihualinxin** [comment]
@MaybeShewill-CV 
训练的时候在根目录生成5张图片
binary_label.png
![binary_label](https://user-images.githubusercontent.com/13042809/45482243-10c76500-b780-11e8-89ea-5967f8332434.png)
binary_seg_img.png
![binary_seg_img](https://user-images.githubusercontent.com/13042809/45482254-18870980-b780-11e8-8ea1-6f02b39a251c.png)

embedding.png
![embedding](https://user-images.githubusercontent.com/13042809/45482267-2177db00-b780-11e8-98ac-ac5661091cc3.png)

image.png
![image](https://user-images.githubusercontent.com/13042809/45482275-289ee900-b780-11e8-886b-b681d082920a.png)

instance_label.png
![instance_label](https://user-images.githubusercontent.com/13042809/45482282-305e8d80-b780-11e8-92f3-292abe189aca.png)

**Comment by baihualinxin** [comment]
@MaybeShewill-CV  图像的大小是1280*720 。。是不是要缩放到 512*256

**Comment by baihualinxin** [comment]
@MaybeShewill-CV  
用 cv2.resize 把三种图片都是缩放了 512 216了 还是不行啊 报错
```
Traceback (most recent call last):
  File "tools/train_lanenet.py", line 308, in <module>
    train_net(args.dataset_dir, args.weights_path, net_flag=args.net)
  File "tools/train_lanenet.py", line 191, in train_net
    gt_imgs, binary_gt_labels, instance_gt_labels = train_dataset.next_batch(CFG.TRAIN.BATCH_SIZE)
  File "G:\lanenet-lane-detection-master\data_provider\lanenet_data_processor.py", line 95, in next_batch
    return self.next_batch(batch_size)
  File "G:\lanenet-lane-detection-master\data_provider\lanenet_data_processor.py", line 95, in next_batch
    return self.next_batch(batch_size)
  File "G:\lanenet-lane-detection-master\data_provider\lanenet_data_processor.py", line 95, in next_batch
    return self.next_batch(batch_size)
  [Previous line repeated 987 more times]
  File "G:\lanenet-lane-detection-master\data_provider\lanenet_data_processor.py", line 93, in next_batch
    self._random_dataset()
  File "G:\lanenet-lane-detection-master\data_provider\lanenet_data_processor.py", line 66, in _random_dataset
    random_idx = np.random.permutation(len(self._gt_img_list))
  File "mtrand.pyx", line 4907, in mtrand.RandomState.permutation
  File "mtrand.pyx", line 4824, in mtrand.RandomState.shuffle
  File "D:\Anaconda3\envs\tensorflow-gpu1\lib\site-packages\numpy\core\_internal.py", line 254, in __init__
    if self._arr.ndim == 0:
RecursionError: maximum recursion depth exceeded in comparison
```

**Comment by MaybeShewill-CV** [comment]
@baihualinxin 你这错误是获取训练数据next batch递归错误,你需要去看看next batch调用有什么问题

**Comment by baihualinxin** [comment]
@MaybeShewill-CV 
lanenet_hnet_data_processor.py 里边的next_batch 这个错误嘛？？？

如果是  lanenet_hnet_data_processor  根本跑不起来，我在这个基础上改的，生成的三种图片的

**Comment by baihualinxin** [comment]
@MaybeShewill-CV 
lanenet_hnet_data_processor.py  就不能公开一个可以用的
 让我这样的小白。。根本不知道问题所在

**Comment by MaybeShewill-CV** [comment]
@baihualinxin 你不需要用这个啊。。。这是训练hnet用的 你不需要这个文件啊＝＝！

**Comment by MaybeShewill-CV** [comment]
@baihualinxin 这个文件根本不是用来制作数据集的 数据集需要你自己构建。data_provider文件夹里存放的是训练过程中生成batch训练数据的工具。你没搞清楚这之间的关系吧＝＝！

**Comment by baihualinxin** [comment]
@MaybeShewill-CV 
我明白你的意思了

读取json文件个逻辑
```
{
  "lanes": [
        [-2, -2, -2, -2, 632, 625, 617, 609, 601, 594, 586, 578, 570, 563, 555, 547, 539, 532, 524, 516, 508, 501, 493, 485, 477, 469, 462, 454, 446, 438, 431, 423, 415, 407, 400, 392, 384, 376, 369, 361, 353, 345, 338, 330, 322, 314, 307, 299],
        [-2, -2, -2, -2, 719, 734, 748, 762, 777, 791, 805, 820, 834, 848, 863, 877, 891, 906, 920, 934, 949, 963, 978, 992, 1006, 1021, 1035, 1049, 1064, 1078, 1092, 1107, 1121, 1135, 1150, 1164, 1178, 1193, 1207, 1221, 1236, 1250, 1265, -2, -2, -2, -2, -2],
        [-2, -2, -2, -2, -2, 532, 503, 474, 445, 416, 387, 358, 329, 300, 271, 241, 212, 183, 154, 125, 96, 67, 38, 9, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2],
        [-2, -2, -2, 781, 822, 862, 903, 944, 984, 1025, 1066, 1107, 1147, 1188, 1229, 1269, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2]
       ],
  "h_samples": [240, 250, 260, 270, 280, 290, 300, 310, 320, 330, 340, 350, 360, 370, 380, 390, 400, 410, 420, 430, 440, 450, 460, 470, 480, 490, 500, 510, 520, 530, 540, 550, 560, 570, 580, 590, 600, 610, 620, 630, 640, 650, 660, 670, 680, 690, 700, 710],
  "raw_file": "path_to_clip"
}
```
```
-2的不要 。lanes 取出一组。。第一组数据取一个，跟h_samples第一个组合。这样的
[632,240]
[625,250]
[617,260]
lanes第二组 跟h_samples组合
[719,240]
[734,250]
[748,260]
```

_这的组合 相连成线是否有问题_
生成一张1280*720的单通道全0的图片
根据坐标改成255
是否就是二进制分段

我没有明白 二进制分段是什么意思。。

**Comment by MaybeShewill-CV** [comment]
@baihualinxin 我也不明白你说的二进制分段什么意思. 既然你能把车道线坐标组合好那你就可以制作数据集了啊

**Comment by baihualinxin** [comment]
@MaybeShewill-CV 
这个制作数据集的方法对嘛？

**Comment by MaybeShewill-CV** [comment]
@baihualinxin 我建议你先去学点基础的东西

**Comment by baihualinxin** [comment]
@MaybeShewill-CV 
 一句话 能清楚的问题，墨迹半天。。
 带着你的答案 进棺材里边吧。。 
 都是一群什么臭毛病

一堆bug玩意 还公开，一个方法都不说不清楚， 还装JB大神。

**Comment by MaybeShewill-CV** [comment]
@baihualinxin 哈哈 就喜欢看你跪求别人代码 还跑步起来 气急败坏的样子

**Comment by MaybeShewill-CV** [comment]
@baihualinxin 就喜欢看你跪求别人代码还跑不起来气急败坏的样子 loser
